### Notebook 26

# **Regions of Interest Statistical Tests**

## **1. Machine Learning**

We perform **Wilcoxon signed-rank tests** on the results of the machine learning models for the classification and regression tasks.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import pickle
import scipy
import pingouin
import os

In [2]:
# Define the preprocessed data path. 
preprocessed_data_path = '../neuropolis-x1_preprocessed_data/'

# Define the results path. 
results_path = '../neuropolis-x1_results/'

In [3]:
# Load the targets. 
with open(preprocessed_data_path + 'dict_targets.p', 'rb') as file:
    dict_targets = pickle.load(file)
with open(preprocessed_data_path + 'classification/dict_targets_classification_sequence.p', 'rb') as file:
    dict_targets_class = pickle.load(file)
with open(preprocessed_data_path + 'regression/dict_targets_regression_sequence.p', 'rb') as file:
    dict_targets_reg = pickle.load(file)
with open(preprocessed_data_path + 'classification/dict_targets_classification_basis.p', 'rb') as file:
    dict_targets_foundation_models = pickle.load(file)

# Define the list of subjects, removing sub-xp102 who has a missing condition. 
subjects = ['sub-xp1' + str(x).zfill(2) for x in range(1, 11)]
subjects.remove('sub-xp102')
subject = subjects[0]

# Retrieve and display the brain region names and the number of brain regions. 
brain_regions = list(dict_targets[subject]['eegfmriNF'].keys())
print(brain_regions)
print(len(brain_regions), 'brain regions')

['Background', 'Frontal Pole', 'Insular Cortex', 'Superior Frontal Gyrus', 'Middle Frontal Gyrus', 'Inferior Frontal Gyrus, pars triangularis', 'Inferior Frontal Gyrus, pars opercularis', 'Precentral Gyrus', 'Temporal Pole', 'Superior Temporal Gyrus, anterior division', 'Superior Temporal Gyrus, posterior division', 'Middle Temporal Gyrus, anterior division', 'Middle Temporal Gyrus, posterior division', 'Middle Temporal Gyrus, temporooccipital part', 'Inferior Temporal Gyrus, anterior division', 'Inferior Temporal Gyrus, posterior division', 'Inferior Temporal Gyrus, temporooccipital part', 'Postcentral Gyrus', 'Superior Parietal Lobule', 'Supramarginal Gyrus, anterior division', 'Supramarginal Gyrus, posterior division', 'Angular Gyrus', 'Lateral Occipital Cortex, superior division', 'Lateral Occipital Cortex, inferior division', 'Intracalcarine Cortex', 'Frontal Medial Cortex', 'Juxtapositional Lobule Cortex (formerly Supplementary Motor Cortex)', 'Subcallosal Cortex', 'Paracingulate Gyrus', 'Cingulate Gyrus, anterior division', 'Cingulate Gyrus, posterior division', 'Precuneous Cortex', 'Cuneal Cortex', 'Frontal Orbital Cortex', 'Parahippocampal Gyrus, anterior division', 'Parahippocampal Gyrus, posterior division', 'Lingual Gyrus', 'Temporal Fusiform Cortex, anterior division', 'Temporal Fusiform Cortex, posterior division', 'Temporal Occipital Fusiform Cortex', 'Occipital Fusiform Gyrus', 'Frontal Opercular Cortex', 'Central Opercular Cortex', 'Parietal Opercular Cortex', 'Planum Polare', "Heschl's Gyrus (includes H1 and H2)", 'Planum Temporale', 'Supracalcarine Cortex', 'Occipital Pole']
49 brain regions

In [4]:
# Define a function to create the DataFrame for the statistical tests. 
def create_df(dict_targets, dict_predictions, brain_regions, score_type, model_type, test_set):

    # Define Pandas DataFrames to store the results. 
    df = pd.DataFrame(columns = ['subject', 'brain_region', 'model_' + score_type, 'baseline_' + score_type])
    counter = 0

    # Iterate through all subjects. 
    for subject in subjects:

        # Iterate through all brain regions. 
        for brain_region_index in range(len(brain_regions)):

            # Fill the DataFrame with the subject and brain region. 
            df.loc[counter, 'subject'] = subject
            df.loc[counter, 'brain_region'] = brain_regions[brain_region_index]

            # Retrieve the targets and predictions values for the current subject and brain region. 
            targets_values = dict_targets[subject][test_set][:, brain_region_index]
            if model_type == 'machine_learning':
                predictions_values = dict_predictions[subject][test_set][:, brain_region_index]
            elif model_type == 'deep_learning':
                predictions_values = dict_predictions[subject][:, brain_region_index]

            # For the classification task, compute the accuracy. 
            if score_type == 'accuracy':
                model_score = np.mean(targets_values == predictions_values)
                baseline_score = np.mean(targets_values == 1)
                
            # For the regression task, compute the mean absolute error (MAE).
            elif score_type == 'MAE':
                model_score = np.mean(np.abs(targets_values - predictions_values))
                baseline_score = np.mean(np.abs(targets_values - np.mean(targets_values)))

            # Fill the DataFrame with the model score and baseline score. 
            df.loc[counter, 'model_' + score_type] = model_score
            df.loc[counter, 'baseline_' + score_type] = baseline_score

            # Increment. 
            counter += 1

    # Return the DataFrame. 
    return df

In [5]:
# Example: Load the machine learning results for the classification task. 
with open(results_path + 'classification/dict_predictions_lr.p', 'rb') as file:
    dict_predictions_lr_class = pickle.load(file)
    
# Example: Create and display the DataFrame for the logistic regression model. 
df_lr_class = create_df(dict_targets_class, dict_predictions_lr_class, brain_regions, 'accuracy', 'machine_learning', 'fmriNF')
df_lr_class

,subject,brain_region,model_accuracy,baseline_accuracy
0,sub-xp101,Background,0.448454,0.5
1,sub-xp101,Frontal Pole,0.42268,0.561856
2,sub-xp101,Insular Cortex,0.525773,0.489691
3,sub-xp101,Superior Frontal Gyrus,0.494845,0.505155
4,sub-xp101,Middle Frontal Gyrus,0.474227,0.530928
...,...,...,...,...
436,sub-xp110,Planum Polare,0.479381,0.494845
437,sub-xp110,Heschl's Gyrus (includes H1 and H2),0.5,0.489691
438,sub-xp110,Planum Temporale,0.525773,0.489691
439,sub-xp110,Supracalcarine Cortex,0.536082,0.479381
440,sub-xp110,Occipital Pole,0.515464,0.5

In [6]:
# Example: Retrieve only the rows corresponding to the region 'Frontal Pole'. 
df_lr_class_frontal_pole = df_lr_class[df_lr_class['brain_region'] == 'Frontal Pole']
df_lr_class_frontal_pole

       subject  brain_region model_accuracy baseline_accuracy
1    sub-xp101  Frontal Pole        0.42268          0.561856
50   sub-xp103  Frontal Pole       0.530928          0.520619
99   sub-xp104  Frontal Pole            0.5          0.489691
148  sub-xp105  Frontal Pole       0.515464               0.5
197  sub-xp106  Frontal Pole       0.597938          0.551546
246  sub-xp107  Frontal Pole       0.592784          0.515464
295  sub-xp108  Frontal Pole       0.587629          0.484536
344  sub-xp109  Frontal Pole       0.541237          0.530928
393  sub-xp110  Frontal Pole       0.572165          0.530928

In [7]:
# Define a function to perform a Wilcoxon signed-rank test. 
def wilcoxon_test(df, score_type, brain_regions):

    # Create empty DataFrames to store the statistics. 
    statistics_scipy = pd.DataFrame()
    statistics_pingouin = pd.DataFrame()

    # Iterate through all brain regions. 
    for brain_region in brain_regions:

        # Retrieve only the rows of df where the column brain_region is equal to the current brain region. 
        roi_df = df[df['brain_region'] == brain_region]

        # Compute the mean and standard deviation of the model and the baseline. 
        mean_model_score = roi_df['model_' + score_type].mean()
        mean_baseline_score = roi_df['baseline_' + score_type].mean()
        std_model_score = roi_df['model_' + score_type].std()
        std_baseline_score = roi_df['baseline_' + score_type].std()

        # Perform the Wilcoxon signed-rank test using SciPy. 
        x = roi_df['model_' + score_type].astype(float).values
        y = roi_df['baseline_' + score_type].astype(float).values
        if score_type == 'accuracy':
            wilcoxon_stat, p_value = scipy.stats.wilcoxon(x, y, alternative = 'greater')
        elif score_type == 'MAE':
            wilcoxon_stat, p_value = scipy.stats.wilcoxon(x, y, alternative = 'less')

        # Compute the confidence interval of the mean. 
        res = scipy.stats.bootstrap((roi_df['model_' + score_type],), np.mean, confidence_level = 0.95)
        ci_low, ci_high = res.confidence_interval

        # Store the statistics in a DataFrame. 
        roi_statistics_scipy = pd.DataFrame([{
            'brain_region': brain_region, 
            'N': len(roi_df),
            'mean_model_' + score_type: mean_model_score,
            'mean_baseline_' + score_type: mean_baseline_score,
            'std_model_' + score_type: std_model_score,
            'std_baseline_' + score_type: std_baseline_score,
            'wilcoxon_stat': wilcoxon_stat,
            'p_value': p_value,
            'ci_low': ci_low, 
            'ci_high': ci_high
        }])

        # Perform the same test using Pingouin to obtain the RBC (Rank-Biserial Correlation) and CLES (Common Language Effect Size). 
        if score_type == 'accuracy':
            roi_statistics_pingouin = pingouin.wilcoxon(x, y, alternative = 'greater')
        elif score_type == 'MAE':
            roi_statistics_pingouin = pingouin.wilcoxon(y, x, alternative = 'greater') # Invert x and y for MAE to get the correct effect size direction. 
        
        # Add the brain region name to the Pingouin statistics DataFrame. 
        roi_statistics_pingouin.insert(0, 'brain_region', brain_region)
        
        # Concatenate the statistics to the main DataFrames. 
        statistics_scipy = pd.concat([statistics_scipy, roi_statistics_scipy], ignore_index = True)
        statistics_pingouin = pd.concat([statistics_pingouin, roi_statistics_pingouin], ignore_index = True)
    
    # Return the statistics. 
    return statistics_scipy, statistics_pingouin

In [8]:
# Perform the Wilcoxon signed-rank test. 
statistics_scipy_lr_class, statistics_pingouin_lr_class = wilcoxon_test(df_lr_class, 'accuracy', brain_regions)

In [9]:
# Display the SciPy statistics. 
statistics_scipy_lr_class

,brain_region,N,mean_model_accuracy,mean_baseline_accuracy,std_model_accuracy,std_baseline_accuracy,wilcoxon_stat,p_value,ci_low,ci_high
0,Background,9,0.537228,0.404353,0.046874,0.053637,44.0,0.003906,0.504573,0.562454
1,Frontal Pole,9,0.540092,0.520619,0.056453,0.026410,36.0,0.060547,0.495991,0.567583
2,Insular Cortex,9,0.532646,0.520619,0.028700,0.030277,31.0,0.171875,0.518900,0.556701
3,Superior Frontal Gyrus,9,0.529210,0.517182,0.030386,0.020457,28.5,0.251953,0.510882,0.548110
4,Middle Frontal Gyrus,9,0.549255,0.507446,0.042904,0.021581,39.0,0.027344,0.522080,0.575029
5,"Inferior Frontal Gyrus, pars triangularis",9,0.507446,0.509164,0.029399,0.012301,18.5,0.484375,0.488545,0.524628
6,"Inferior Frontal Gyrus, pars opercularis",9,0.523482,0.513173,0.039687,0.021270,26.0,0.355469,0.497136,0.546392
7,Precentral Gyrus,9,0.548110,0.518328,0.033899,0.025135,38.0,0.037109,0.522910,0.565865
8,Temporal Pole,9,0.541237,0.519473,0.027639,0.030796,37.5,0.039062,0.525773,0.560137
9,"Superior Temporal Gyrus, anterior division",9,0.499427,0.497136,0.025442,0.018062,23.5,0.466797,0.483963,0.515464
10,"Superior Temporal Gyrus, posterior division",9,0.518900,0.512027,0.051546,0.030167,24.0,0.455078,0.488545,0.550974
11,"Middle Temporal Gyrus, anterior division",9,0.516037,0.500000,0.033845,0.025514,21.0,0.140625,0.495991,0.537228
12,"Middle Temporal Gyrus, posterior division",9,0.529210,0.484536,0.030056,0.020457,43.0,0.005859,0.505704,0.544674
13,"Middle Temporal Gyrus, temporooccipital part",9,0.532646,0.491982,0.031775,0.016323,28.0,0.007812,0.513173,0.552692
14,"Inferior Temporal Gyrus, anterior division",9,0.522910,0.488545,0.036368,0.015841,39.5,0.021484,0.498282,0.543528
15,"Inferior Temporal Gyrus, posterior division",9,0.538946,0.479381,0.036276,0.029835,41.0,0.015625,0.517182,0.563001
16,"Inferior Temporal Gyrus, temporooccipital part",9,0.528637,0.483391,0.052384,0.018184,38.0,0.037109,0.496564,0.560710
17,Postcentral Gyrus,9,0.530928,0.514318,0.035526,0.028674,34.5,0.087891,0.508591,0.552119
18,Superior Parietal Lobule,9,0.529210,0.508018,0.055756,0.016725,25.0,0.191406,0.497709,0.565865
19,"Supramarginal Gyrus, anterior division",9,0.537228,0.509164,0.039575,0.026881,36.0,0.064453,0.516609,0.565865
20,"Supramarginal Gyrus, posterior division",9,0.517182,0.500000,0.066413,0.026908,31.0,0.179688,0.468499,0.552692
21,Angular Gyrus,9,0.503436,0.517755,0.023339,0.026298,14.0,0.849609,0.489691,0.518328
22,"Lateral Occipital Cortex, superior division",9,0.549255,0.508591,0.033417,0.025384,40.0,0.019531,0.525773,0.568156
23,"Lateral Occipital Cortex, inferior division",9,0.517755,0.484536,0.037801,0.017669,40.5,0.017578,0.496564,0.542955
24,Intracalcarine Cortex,9,0.565865,0.484536,0.037061,0.026284,45.0,0.001953,0.548110,0.595074
25,Frontal Medial Cortex,9,0.509737,0.488545,0.039798,0.022138,32.0,0.150391,0.488545,0.538373
26,Juxtapositional Lobule Cortex (formerly Supple...,9,0.536655,0.509164,0.041192,0.018184,27.5,0.101562,0.514318,0.564719
27,Subcallosal Cortex,9,0.533219,0.488545,0.026171,0.021836,45.0,0.001953,0.516037,0.548110
28,Paracingulate Gyrus,9,0.525773,0.506873,0.043281,0.024451,32.0,0.150391,0.500573,0.553837
29,"Cingulate Gyrus, anterior division",9,0.543528,0.509737,0.034396,0.024511,26.0,0.023438,0.525200,0.569301
30,"Cingulate Gyrus, posterior division",9,0.518328,0.513173,0.033714,0.034008,23.0,0.488281,0.494273,0.536082
31,Precuneous Cortex,9,0.523482,0.509164,0.047321,0.029361,13.5,0.312500,0.496564,0.556128
32,Cuneal Cortex,9,0.546392,0.479954,0.033206,0.029549,44.0,0.003906,0.526346,0.566438
33,Frontal Orbital Cortex,9,0.514318,0.491409,0.053741,0.017480,33.0,0.121094,0.486827,0.556128
34,"Parahippocampal Gyrus, anterior division",9,0.505727,0.501718,0.039965,0.041156,22.0,0.544922,0.483963,0.533219
35,"Parahippocampal Gyrus, posterior division",9,0.525200,0.499427,0.031612,0.025311,36.0,0.064453,0.503436,0.542692
36,Lingual Gyrus,9,0.545819,0.495418,0.047554,0.019191,39.0,0.025391,0.513173,0.571592
37,"Temporal Fusiform Cortex, anterior division",9,0.483391,0.501718,0.053555,0.041398,13.0,0.867188,0.447881,0.513746
38,"Temporal Fusiform Cortex, posterior division",9,0.510882,0.498282,0.030325,0.032191,31.0,0.171875,0.493700,0.530928
39,Temporal Occipital Fusiform Cortex,9,0.526919,0.504009,0.047298,0.020093,31.0,0.171875,0.505155,0.567158
40,Occipital Fusiform Gyrus,9,0.536655,0.494845,0.041353,0.020130,38.5,0.029297,0.511455,0.561856
41,Frontal Opercular Cortex,9,0.521191,0.508018,0.042541,0.017311,28.5,0.259766,0.500000,0.555556
42,Central Opercular Cortex,9,0.523482,0.513173,0.037888,0.017877,29.0,0.248047,0.501718,0.548110
43,Parietal Opercular Cortex,9,0.523482,0.516609,0.051230,0.040158,24.0,0.455078,0.488545,0.552119
44,Planum Polare,9,0.505727,0.510309,0.036580,0.025514,20.0,0.632812,0.482245,0.527491
45,Heschl's Gyrus (includes H1 and H2),9,0.508591,0.520619,0.034095,0.019964,14.5,0.828125,0.490263,0.533219
46,Planum Temporale,9,0.506873,0.514318,0.043050,0.021374,18.5,0.685547,0.473654,0.529210
47,Supracalcarine Cortex,9,0.519473,0.490263,0.037771,0.021009,24.0,0.054688,0.500000,0.547537
48,Occipital Pole,9,0.518900,0.498282,0.041237,0.011811,36.0,0.064453,0.494273,0.544925

In [10]:
# Display the Pingouin statistics. 
statistics_pingouin_lr_class

,brain_region,W-val,alternative,p-val,RBC,CLES
0,Background,44.0,greater,0.003906,0.955556,0.981481
1,Frontal Pole,36.0,greater,0.060547,0.600000,0.679012
2,Insular Cortex,31.0,greater,0.171875,0.377778,0.561728
3,Superior Frontal Gyrus,28.5,greater,0.251953,0.266667,0.617284
4,Middle Frontal Gyrus,39.0,greater,0.027344,0.733333,0.814815
5,"Inferior Frontal Gyrus, pars triangularis",18.5,greater,0.484375,0.027778,0.518519
6,"Inferior Frontal Gyrus, pars opercularis",26.0,greater,0.355469,0.155556,0.641975
7,Precentral Gyrus,38.0,greater,0.037109,0.688889,0.814815
8,Temporal Pole,37.5,greater,0.039062,0.666667,0.691358
9,"Superior Temporal Gyrus, anterior division",23.5,greater,0.466797,0.044444,0.518519
10,"Superior Temporal Gyrus, posterior division",24.0,greater,0.455078,0.066667,0.586420
11,"Middle Temporal Gyrus, anterior division",21.0,greater,0.140625,0.500000,0.629630
12,"Middle Temporal Gyrus, posterior division",43.0,greater,0.005859,0.911111,0.895062
13,"Middle Temporal Gyrus, temporooccipital part",28.0,greater,0.007812,1.000000,0.882716
14,"Inferior Temporal Gyrus, anterior division",39.5,greater,0.021484,0.755556,0.820988
15,"Inferior Temporal Gyrus, posterior division",41.0,greater,0.015625,0.822222,0.870370
16,"Inferior Temporal Gyrus, temporooccipital part",38.0,greater,0.037109,0.688889,0.783951
17,Postcentral Gyrus,34.5,greater,0.087891,0.533333,0.654321
18,Superior Parietal Lobule,25.0,greater,0.191406,0.388889,0.648148
19,"Supramarginal Gyrus, anterior division",36.0,greater,0.064453,0.600000,0.703704
20,"Supramarginal Gyrus, posterior division",31.0,greater,0.179688,0.377778,0.592593
21,Angular Gyrus,14.0,greater,0.849609,-0.377778,0.327160
22,"Lateral Occipital Cortex, superior division",40.0,greater,0.019531,0.777778,0.839506
23,"Lateral Occipital Cortex, inferior division",40.5,greater,0.017578,0.800000,0.858025
24,Intracalcarine Cortex,45.0,greater,0.001953,1.000000,1.000000
25,Frontal Medial Cortex,32.0,greater,0.150391,0.422222,0.604938
26,Juxtapositional Lobule Cortex (formerly Supple...,27.5,greater,0.101562,0.527778,0.722222
27,Subcallosal Cortex,45.0,greater,0.001953,1.000000,0.925926
28,Paracingulate Gyrus,32.0,greater,0.150391,0.422222,0.617284
29,"Cingulate Gyrus, anterior division",26.0,greater,0.023438,0.857143,0.796296
30,"Cingulate Gyrus, posterior division",23.0,greater,0.488281,0.022222,0.543210
31,Precuneous Cortex,13.5,greater,0.312500,0.285714,0.586420
32,Cuneal Cortex,44.0,greater,0.003906,0.955556,0.950617
33,Frontal Orbital Cortex,33.0,greater,0.121094,0.466667,0.641975
34,"Parahippocampal Gyrus, anterior division",22.0,greater,0.544922,-0.022222,0.537037
35,"Parahippocampal Gyrus, posterior division",36.0,greater,0.064453,0.600000,0.728395
36,Lingual Gyrus,39.0,greater,0.025391,0.733333,0.870370
37,"Temporal Fusiform Cortex, anterior division",13.0,greater,0.867188,-0.422222,0.419753
38,"Temporal Fusiform Cortex, posterior division",31.0,greater,0.171875,0.377778,0.574074
39,Temporal Occipital Fusiform Cortex,31.0,greater,0.171875,0.377778,0.709877
40,Occipital Fusiform Gyrus,38.5,greater,0.029297,0.711111,0.833333
41,Frontal Opercular Cortex,28.5,greater,0.259766,0.266667,0.598765
42,Central Opercular Cortex,29.0,greater,0.248047,0.288889,0.549383
43,Parietal Opercular Cortex,24.0,greater,0.455078,0.066667,0.549383
44,Planum Polare,20.0,greater,0.632812,-0.111111,0.469136
45,Heschl's Gyrus (includes H1 and H2),14.5,greater,0.828125,-0.355556,0.339506
46,Planum Temporale,18.5,greater,0.685547,-0.177778,0.487654
47,Supracalcarine Cortex,24.0,greater,0.054688,0.714286,0.740741
48,Occipital Pole,36.0,greater,0.064453,0.600000,0.722222

In [11]:
# Define a function to create a summary DataFrame. 
def create_summary_df(model_names, score_type, brain_regions):
    
    # Create the summary DataFrame with a double index: model name and brain region. 
    df_summary = pd.DataFrame(index = pd.MultiIndex.from_product([model_names, brain_regions], names=['model', 'brain region']),
                              columns = ['N', 
                                         'mean model ' + score_type, 
                                         'mean baseline ' + score_type, 
                                         'STD model ' + score_type,
                                         'STD baseline ' + score_type,
                                         'Wilcoxon W statistic', 
                                         'p-value', 
                                         'CI (lower)',
                                         'CI (upper)', 
                                         'RBC', 
                                         'CLES'])
    
    return df_summary

In [12]:
# Display an example of empty summary DataFrame. 
create_summary_df(['Logistic Regression', 'K-Nearest Neighbors'], 'accuracy', brain_regions)

                                                           N  \
model               brain region
Logistic Regression Background                           NaN
                    Frontal Pole                         NaN
                    Insular Cortex                       NaN
                    Superior Frontal Gyrus               NaN
                    Middle Frontal Gyrus                 NaN
...                                                      ...
K-Nearest Neighbors Planum Polare                        NaN
                    Heschl's Gyrus (includes H1 and H2)  NaN
                    Planum Temporale                     NaN
                    Supracalcarine Cortex                NaN
                    Occipital Pole                       NaN

                                                        mean model accuracy  \
model               brain region
Logistic Regression Background                                          NaN
                    Frontal Pole                                        NaN
                    Insular Cortex                                      NaN
                    Superior Frontal Gyrus                              NaN
                    Middle Frontal Gyrus                                NaN
...                                                                     ...
K-Nearest Neighbors Planum Polare                                       NaN
                    Heschl's Gyrus (includes H1 and H2)                 NaN
                    Planum Temporale                                    NaN
                    Supracalcarine Cortex                               NaN
                    Occipital Pole                                      NaN

                                                        mean baseline accuracy  \
model               brain region
Logistic Regression Background                                             NaN
                    Frontal Pole                                           NaN
                    Insular Cortex                                         NaN
                    Superior Frontal Gyrus                                 NaN
                    Middle Frontal Gyrus                                   NaN
...                                                                        ...
K-Nearest Neighbors Planum Polare                                          NaN
                    Heschl's Gyrus (includes H1 and H2)                    NaN
                    Planum Temporale                                       NaN
                    Supracalcarine Cortex                                  NaN
                    Occipital Pole                                         NaN

                                                        STD model accuracy  \
model               brain region
Logistic Regression Background                                         NaN
                    Frontal Pole                                       NaN
                    Insular Cortex                                     NaN
                    Superior Frontal Gyrus                             NaN
                    Middle Frontal Gyrus                               NaN
...                                                                    ...
K-Nearest Neighbors Planum Polare                                      NaN
                    Heschl's Gyrus (includes H1 and H2)                NaN
                    Planum Temporale                                   NaN
                    Supracalcarine Cortex                              NaN
                    Occipital Pole                                     NaN

                                                        STD baseline accuracy  \
model               brain region
Logistic Regression Background                                            NaN
                    Frontal Pole                                          NaN
                    Insular Cortex                                        NaN
                    Superior Frontal Gyrus                                NaN
                    Middle Frontal Gyrus                                  NaN
...                                                                       ...
K-Nearest Neighbors Planum Polare                                         NaN
                    Heschl's Gyrus (includes H1 and H2)                   NaN
                    Planum Temporale                                      NaN
                    Supracalcarine Cortex                                 NaN
                    Occipital Pole                                        NaN

                                                        Wilcoxon W statistic  \
model               brain region
Logistic Regression Background                                           NaN
                    Frontal Pole                                         NaN
                    Insular Cortex                                       NaN
                    Superior Frontal Gyrus                               NaN
                    Middle Frontal Gyrus                                 NaN
...                                                                      ...
K-Nearest Neighbors Planum Polare                                        NaN
                    Heschl's Gyrus (includes H1 and H2)                  NaN
                    Planum Temporale                                     NaN
                    Supracalcarine Cortex                                NaN
                    Occipital Pole                                       NaN

                                                        p-value CI (lower)  \
model               brain region
Logistic Regression Background                              NaN        NaN
                    Frontal Pole                            NaN        NaN
                    Insular Cortex                          NaN        NaN
                    Superior Frontal Gyrus                  NaN        NaN
                    Middle Frontal Gyrus                    NaN        NaN
...                                                         ...        ...
K-Nearest Neighbors Planum Polare                           NaN        NaN
                    Heschl's Gyrus (includes H1 and H2)     NaN        NaN
                    Planum Temporale                        NaN        NaN
                    Supracalcarine Cortex                   NaN        NaN
                    Occipital Pole                          NaN        NaN

                                                        CI (upper)  RBC CLES
model               brain region
Logistic Regression Background                                 NaN  NaN  NaN
                    Frontal Pole                               NaN  NaN  NaN
                    Insular Cortex                             NaN  NaN  NaN
                    Superior Frontal Gyrus                     NaN  NaN  NaN
                    Middle Frontal Gyrus                       NaN  NaN  NaN
...                                                            ...  ...  ...
K-Nearest Neighbors Planum Polare                              NaN  NaN  NaN
                    Heschl's Gyrus (includes H1 and H2)        NaN  NaN  NaN
                    Planum Temporale                           NaN  NaN  NaN
                    Supracalcarine Cortex                      NaN  NaN  NaN
                    Occipital Pole                             NaN  NaN  NaN

[98 rows x 11 columns]

In [13]:
# Define a function to store statistics in the summary DataFrame. 
def store_statistics_in_summary_df(df_summary, model_names, model_index, statistics_scipy, statistics_pingouin, score_type, brain_regions):

    # Iterate through all brain regions. 
    for brain_region in brain_regions:

        # Retrieve only the rows of statistics_scipy and statistics_pingouin where the column brain_region is equal to the current brain region. 
        roi_statistics_scipy = statistics_scipy[statistics_scipy['brain_region'] == brain_region]
        roi_statistics_pingouin = statistics_pingouin[statistics_pingouin['brain_region'] == brain_region]

        # Store the statistics in the summary DataFrame. 
        df_summary.loc[(model_names[model_index], brain_region), 'N'] = roi_statistics_scipy['N'].values[0]
        df_summary.loc[(model_names[model_index], brain_region), 'mean model ' + score_type] = roi_statistics_scipy['mean_model_' + score_type].values[0]
        df_summary.loc[(model_names[model_index], brain_region), 'mean baseline ' + score_type] = roi_statistics_scipy['mean_baseline_' + score_type].values[0]
        df_summary.loc[(model_names[model_index], brain_region), 'STD model ' + score_type] = roi_statistics_scipy['std_model_' + score_type].values[0]
        df_summary.loc[(model_names[model_index], brain_region), 'STD baseline ' + score_type] = roi_statistics_scipy['std_baseline_' + score_type].values[0]
        df_summary.loc[(model_names[model_index], brain_region), 'Wilcoxon W statistic'] = roi_statistics_scipy['wilcoxon_stat'].values[0]
        df_summary.loc[(model_names[model_index], brain_region), 'p-value'] = roi_statistics_scipy['p_value'].values[0]
        df_summary.loc[(model_names[model_index], brain_region), 'CI (lower)'] = roi_statistics_scipy['ci_low'].values[0]
        df_summary.loc[(model_names[model_index], brain_region), 'CI (upper)'] = roi_statistics_scipy['ci_high'].values[0]
        df_summary.loc[(model_names[model_index], brain_region), 'RBC'] = roi_statistics_pingouin['RBC'].values[0]
        df_summary.loc[(model_names[model_index], brain_region), 'CLES'] = roi_statistics_pingouin['CLES'].values[0]

        # Ensure the p-value column is numeric, then format it in scientific notation. 
        df_summary['p-value'] = pd.to_numeric(df_summary['p-value'], errors = 'coerce')
        df_summary['p-value'] = df_summary['p-value'].apply(lambda x: f'{x:.2e}')

    return df_summary

In [14]:
# Define a function to perform a Wilcoxon signed-rank test on a series of models. 
def run_wilcoxon_tests(model_names, dict_targets, list_dict_predictions, brain_regions, score_type, model_type, test_set):

    # Create a summary DataFrame to store the statistics for all models. 
    df_summary = create_summary_df(model_names, score_type, brain_regions)

    # Create a dictionary to store the metrics DataFrames for all models. 
    dict_df_metrics = {}

    # Create a dictionary to store all targets and predictions for all models. 
    dict_all_targets_predictions = {}

    # Iterate through all models. 
    for model_index in range(len(model_names)):

        # Create the DataFrame and perform the Wilcoxon signed-rank test. 
        dict_predictions = list_dict_predictions[model_index]
        df = create_df(dict_targets, dict_predictions, brain_regions, score_type, model_type, test_set)
        statistics_scipy, statistics_pingouin = wilcoxon_test(df, score_type, brain_regions)

        # Store the statistics in the summary DataFrame. 
        df_summary = store_statistics_in_summary_df(df_summary, model_names, model_index, statistics_scipy, statistics_pingouin, score_type, brain_regions)

        # Store the metrics DataFrame in the dictionary.
        dict_df_metrics[model_names[model_index]] = df
        
    # Return the summary DataFrame and the dictionary. 
    return df_summary, dict_df_metrics, dict_all_targets_predictions

### Classification

In [15]:
# Define a function to load the machine learning results for the classification task. 
def load_classification_ml_results(cv_iteration):

    if cv_iteration == 1:
        iteration_result_path = results_path + 'classification/'
        test_set = 'fmriNF'
    elif cv_iteration == 2:
        iteration_result_path = results_path + 'classification/cross_validation/cv_iteration_' + str(cv_iteration) + '/'
        test_set = 'eegfmriNF'
    elif cv_iteration == 3:
        iteration_result_path = results_path + 'classification/cross_validation/cv_iteration_' + str(cv_iteration) + '/'
        test_set = 'eegNF'

    # Load the machine learning results for the classification task. 
    with open(iteration_result_path + 'dict_predictions_lr.p', 'rb') as file:
        dict_predictions_lr_class = pickle.load(file)
    with open(iteration_result_path + 'dict_predictions_knn.p', 'rb') as file:
        dict_predictions_knn_class = pickle.load(file)
    with open(iteration_result_path + 'dict_predictions_dt.p', 'rb') as file:
        dict_predictions_dt_class = pickle.load(file)
    with open(iteration_result_path + 'dict_predictions_rf.p', 'rb') as file:
        dict_predictions_rf_class = pickle.load(file)
    with open(iteration_result_path + 'dict_predictions_svm.p', 'rb') as file:
        dict_predictions_svm_class = pickle.load(file)
    with open(iteration_result_path + 'dict_predictions_xgb.p', 'rb') as file:
        dict_predictions_xgb_class = pickle.load(file)

    return [dict_predictions_lr_class, 
            dict_predictions_knn_class, 
            dict_predictions_dt_class, 
            dict_predictions_rf_class, 
            dict_predictions_svm_class, 
            dict_predictions_xgb_class, 
            test_set]

In [16]:
# Define a function to run the tests for machine learning classification models.
def run_classification_ml_tests(cv_iteration, model_names):

    # Load the machine learning results for the classification task.
    dict_predictions_lr_class, dict_predictions_knn_class, dict_predictions_dt_class, dict_predictions_rf_class, dict_predictions_svm_class, dict_predictions_xgb_class, test_set = load_classification_ml_results(cv_iteration)

    predictions_ml_class = [dict_predictions_lr_class, 
                            dict_predictions_knn_class, 
                            dict_predictions_dt_class, 
                            dict_predictions_rf_class, 
                            dict_predictions_svm_class, 
                            dict_predictions_xgb_class]

    # Run the Wilcoxon signed-rank tests for all models. 
    df_summary_ml_class, dict_df_metrics_ml_class, _ = run_wilcoxon_tests(model_names, dict_targets_class, predictions_ml_class, brain_regions, 'accuracy', 'machine_learning', test_set)
    
    return df_summary_ml_class, dict_df_metrics_ml_class

In [17]:
# Define the machine learning models for classification. 
model_names = ['Logistic Regression', 'K-Nearest Neighbors', 'Decision Tree', 'Random Forest', 'Support Vector Machine', 'XGBoost']

In [18]:
# Iteration 1: run the tests for machine learning classification models. 
cv_iteration = 1
df_summary_ml_class_iteration_1, dict_df_metrics_ml_class_iteration_1 = run_classification_ml_tests(cv_iteration, model_names)

In [19]:
# Iteration 2: run the tests for machine learning classification models. 
cv_iteration = 2
df_summary_ml_class_iteration_2, dict_df_metrics_ml_class_iteration_2 = run_classification_ml_tests(cv_iteration, model_names)

In [20]:
# Iteration 3: run the tests for machine learning classification models. 
cv_iteration = 3
df_summary_ml_class_iteration_3, dict_df_metrics_ml_class_iteration_3 = run_classification_ml_tests(cv_iteration, model_names)

In [21]:
# Create a dictionary to store the pooled metrics DataFrames for all models. 
dict_df_metrics_ml_class_pooled = {}

# Create a summary DataFrame to store the statistics for all models. 
df_summary_ml_class_pooled = create_summary_df(model_names, 'accuracy', brain_regions)

# Iterate through all models. 
for model_name in model_names:

    # Retrieve the model index.
    model_index = model_names.index(model_name)

    # Pool the metrics DataFrames across cross-validation iterations. 
    df_iteration_1 = dict_df_metrics_ml_class_iteration_1[model_name]
    df_iteration_2 = dict_df_metrics_ml_class_iteration_2[model_name]
    df_iteration_3 = dict_df_metrics_ml_class_iteration_3[model_name]
    df_pooled = pd.concat([df_iteration_1, df_iteration_2, df_iteration_3], ignore_index = True)

    # Perform the Wilcoxon signed-rank test. 
    statistics_scipy, statistics_pingouin = wilcoxon_test(df_pooled, 'accuracy', brain_regions)

    # Store the pooled metrics DataFrame in the dictionary. 
    dict_df_metrics_ml_class_pooled[model_name] = df_pooled

    # Store the statistics in the summary DataFrame. 
    df_summary_ml_class_pooled = store_statistics_in_summary_df(df_summary_ml_class_pooled, model_names, model_index, statistics_scipy, statistics_pingouin, 'accuracy', brain_regions)

In [22]:
# Diplay the pooled summary DataFrame. 
df_summary_ml_class_pooled

                                                          N  \
model               brain region
Logistic Regression Background                           27
                    Frontal Pole                         27
                    Insular Cortex                       27
                    Superior Frontal Gyrus               27
                    Middle Frontal Gyrus                 27
...                                                      ..
XGBoost             Planum Polare                        27
                    Heschl's Gyrus (includes H1 and H2)  27
                    Planum Temporale                     27
                    Supracalcarine Cortex                27
                    Occipital Pole                       27

                                                        mean model accuracy  \
model               brain region
Logistic Regression Background                                     0.528255
                    Frontal Pole                                   0.520809
                    Insular Cortex                                   0.5168
                    Superior Frontal Gyrus                         0.520237
                    Middle Frontal Gyrus                           0.527873
...                                                                     ...
XGBoost             Planum Polare                                  0.512791
                    Heschl's Gyrus (includes H1 and H2)            0.514128
                    Planum Temporale                               0.509927
                    Supracalcarine Cortex                            0.5042
                    Occipital Pole                                 0.504773

                                                        mean baseline accuracy  \
model               brain region
Logistic Regression Background                                         0.41428
                    Frontal Pole                                      0.511264
                    Insular Cortex                                    0.522719
                    Superior Frontal Gyrus                            0.518328
                    Middle Frontal Gyrus                              0.512218
...                                                                        ...
XGBoost             Planum Polare                                     0.506682
                    Heschl's Gyrus (includes H1 and H2)               0.517373
                    Planum Temporale                                  0.507064
                    Supracalcarine Cortex                             0.494654
                    Occipital Pole                                    0.507255

                                                        STD model accuracy  \
model               brain region
Logistic Regression Background                                      0.0389
                    Frontal Pole                                  0.048492
                    Insular Cortex                                0.033516
                    Superior Frontal Gyrus                        0.036419
                    Middle Frontal Gyrus                          0.037913
...                                                                    ...
XGBoost             Planum Polare                                 0.033963
                    Heschl's Gyrus (includes H1 and H2)           0.039763
                    Planum Temporale                              0.035509
                    Supracalcarine Cortex                         0.044504
                    Occipital Pole                                 0.03591

                                                        STD baseline accuracy  \
model               brain region
Logistic Regression Background                                       0.044045
                    Frontal Pole                                     0.025092
                    Insular Cortex                                   0.031395
                    Superior Frontal Gyrus                           0.023679
                    Middle Frontal Gyrus                              0.02538
...                                                                       ...
XGBoost             Planum Polare                                    0.023483
                    Heschl's Gyrus (includes H1 and H2)              0.021308
                    Planum Temporale                                 0.021356
                    Supracalcarine Cortex                            0.020393
                    Occipital Pole                                    0.02324

                                                        Wilcoxon W statistic  \
model               brain region
Logistic Regression Background                                         375.0
                    Frontal Pole                                       238.0
                    Insular Cortex                                     161.0
                    Superior Frontal Gyrus                             197.5
                    Middle Frontal Gyrus                               235.5
...                                                                      ...
XGBoost             Planum Polare                                      201.0
                    Heschl's Gyrus (includes H1 and H2)                137.5
                    Planum Temporale                                   207.5
                    Supracalcarine Cortex                              196.5
                    Occipital Pole                                     144.0

                                                          p-value CI (lower)  \
model               brain region
Logistic Regression Background                           3.93e-06     0.5126
                    Frontal Pole                         1.19e-01   0.502406
                    Insular Cortex                       7.50e-01   0.504964
                    Superior Frontal Gyrus               2.88e-01   0.505346
                    Middle Frontal Gyrus                 6.37e-02   0.513937
...                                                           ...        ...
XGBoost             Planum Polare                        2.59e-01   0.499236
                    Heschl's Gyrus (includes H1 and H2)  6.40e-01   0.498855
                    Planum Temporale                     3.28e-01     0.4958
                    Supracalcarine Cortex                1.80e-01   0.488545
                    Occipital Pole                       6.91e-01   0.491791

                                                        CI (upper)       RBC  \
model               brain region
Logistic Regression Background                            0.541619  0.984127
                    Frontal Pole                           0.53761  0.259259
                    Insular Cortex                        0.529401 -0.148148
                    Superior Frontal Gyrus                0.532264  0.125356
                    Middle Frontal Gyrus                  0.542383   0.34188
...                                                            ...       ...
XGBoost             Planum Polare                         0.524055  0.145299
                    Heschl's Gyrus (includes H1 and H2)   0.528736 -0.083333
                    Planum Temporale                      0.522146  0.097884
                    Supracalcarine Cortex                 0.521573  0.209231
                    Occipital Pole                        0.518519 -0.113846

                                                             CLES
model               brain region
Logistic Regression Background                           0.971193
                    Frontal Pole                          0.58642
                    Insular Cortex                       0.430727
                    Superior Frontal Gyrus               0.552812
                    Middle Frontal Gyrus                 0.650206
...                                                           ...
XGBoost             Planum Polare                        0.580247
                    Heschl's Gyrus (includes H1 and H2)  0.473937
                    Planum Temporale                      0.55487
                    Supracalcarine Cortex                0.530864
                    Occipital Pole                       0.472565

[294 rows x 11 columns]

### Regression

In [23]:
# Define a function to load the machine learning results for the regression task. 
def load_regression_ml_results(cv_iteration):

    if cv_iteration == 1:
        iteration_result_path = results_path + 'regression/'
        test_set = 'fmriNF'
    elif cv_iteration == 2:
        iteration_result_path = results_path + 'regression/cross_validation/cv_iteration_' + str(cv_iteration) + '/'
        test_set = 'eegfmriNF'
    elif cv_iteration == 3:
        iteration_result_path = results_path + 'regression/cross_validation/cv_iteration_' + str(cv_iteration) + '/'
        test_set = 'eegNF'

    # Load the machine learning results for the regression task. 
    with open(iteration_result_path + 'dict_predictions_lr.p', 'rb') as file:
        dict_predictions_lr_reg = pickle.load(file)
    with open(iteration_result_path + 'dict_predictions_ridge.p', 'rb') as file:
        dict_predictions_ridge_reg = pickle.load(file)
    with open(iteration_result_path + 'dict_predictions_lasso.p', 'rb') as file:
        dict_predictions_lasso_reg = pickle.load(file)
    with open(iteration_result_path + 'dict_predictions_knn.p', 'rb') as file:
        dict_predictions_knn_reg = pickle.load(file)
    with open(iteration_result_path + 'dict_predictions_dt.p', 'rb') as file:
        dict_predictions_dt_reg = pickle.load(file)
    with open(iteration_result_path + 'dict_predictions_rf.p', 'rb') as file:
        dict_predictions_rf_reg = pickle.load(file)
    with open(iteration_result_path + 'dict_predictions_svm.p', 'rb') as file:
        dict_predictions_svm_reg = pickle.load(file)
    with open(iteration_result_path + 'dict_predictions_xgb.p', 'rb') as file:
        dict_predictions_xgb_reg = pickle.load(file)

    return [dict_predictions_lr_reg, 
            dict_predictions_ridge_reg, 
            dict_predictions_lasso_reg, 
            dict_predictions_knn_reg, 
            dict_predictions_dt_reg, 
            dict_predictions_rf_reg, 
            dict_predictions_svm_reg, 
            dict_predictions_xgb_reg, 
            test_set]

In [24]:
# Define a function to run the tests for machine learning regression models.
def run_regression_ml_tests(cv_iteration, model_names):
    
    # Load the machine learning results for the regression task.
    dict_predictions_lr_reg, dict_predictions_ridge_reg, dict_predictions_lasso_reg, dict_predictions_knn_reg, dict_predictions_dt_reg, dict_predictions_rf_reg, dict_predictions_svm_reg, dict_predictions_xgb_reg, test_set = load_regression_ml_results(cv_iteration)

    predictions_ml_reg = [dict_predictions_lr_reg,
                        dict_predictions_ridge_reg, 
                        dict_predictions_lasso_reg, 
                        dict_predictions_knn_reg, 
                        dict_predictions_dt_reg, 
                        dict_predictions_rf_reg, 
                        dict_predictions_svm_reg, 
                        dict_predictions_xgb_reg]

    # Run the Wilcoxon signed-rank tests for all models. 
    df_summary_ml_reg, dict_df_metrics_ml_reg, dict_all_targets_predictions_ml_reg = run_wilcoxon_tests(model_names, dict_targets_reg, predictions_ml_reg, brain_regions, 'MAE', 'machine_learning', test_set)
    
    return df_summary_ml_reg, dict_df_metrics_ml_reg, dict_all_targets_predictions_ml_reg

In [25]:
# Define the machine learning models for regression. 
model_names = ['Linear Regression', 'Ridge Regression', 'Lasso Regression', 'K-Nearest Neighbors', 'Decision Tree', 'Random Forest', 'Support Vector Machine', 'XGBoost']

In [26]:
# Iteration 1: run the tests for machine learning regression models. 
cv_iteration = 1
df_summary_ml_reg_iteration_1, dict_df_metrics_ml_reg_iteration_1, dict_all_targets_predictions_ml_reg_iteration_1 = run_regression_ml_tests(cv_iteration, model_names)

In [27]:
# Iteration 2: run the tests for machine learning regression models. 
cv_iteration = 2
df_summary_ml_reg_iteration_2, dict_df_metrics_ml_reg_iteration_2, dict_all_targets_predictions_ml_reg_iteration_2 = run_regression_ml_tests(cv_iteration, model_names)

In [28]:
# Iteration 3: run the tests for machine learning regression models. 
cv_iteration = 3
df_summary_ml_reg_iteration_3, dict_df_metrics_ml_reg_iteration_3, dict_all_targets_predictions_ml_reg_iteration_3 = run_regression_ml_tests(cv_iteration, model_names)

In [29]:
# Create a dictionary to store the pooled metrics DataFrames for all models. 
dict_df_metrics_ml_reg_pooled = {}

# Create a summary DataFrame to store the statistics for all models. 
df_summary_ml_reg_pooled = create_summary_df(model_names, 'MAE', brain_regions)

# Iterate through all models. 
for model_name in model_names:

    # Retrieve the model index.
    model_index = model_names.index(model_name)

    # Pool the metrics DataFrames across cross-validation iterations. 
    df_iteration_1 = dict_df_metrics_ml_reg_iteration_1[model_name]
    df_iteration_2 = dict_df_metrics_ml_reg_iteration_2[model_name]
    df_iteration_3 = dict_df_metrics_ml_reg_iteration_3[model_name]
    df_pooled = pd.concat([df_iteration_1, df_iteration_2, df_iteration_3], ignore_index = True)

    # Perform the Wilcoxon signed-rank test. 
    statistics_scipy, statistics_pingouin = wilcoxon_test(df_pooled, 'MAE', brain_regions)

    # Store the pooled metrics DataFrame in the dictionary. 
    dict_df_metrics_ml_reg_pooled[model_name] = df_pooled

    # Store the statistics in the summary DataFrame. 
    df_summary_ml_reg_pooled = store_statistics_in_summary_df(df_summary_ml_reg_pooled, model_names, model_index, statistics_scipy, statistics_pingouin, 'MAE', brain_regions)

In [30]:
# Diplay the pooled summary DataFrame. 
df_summary_ml_reg_pooled

                                                        N mean model MAE  \
model             brain region
Linear Regression Background                           27       0.840808
                  Frontal Pole                         27       0.905702
                  Insular Cortex                       27       0.894583
                  Superior Frontal Gyrus               27       0.855446
                  Middle Frontal Gyrus                 27       0.904246
...                                                    ..            ...
XGBoost           Planum Polare                        27       0.835909
                  Heschl's Gyrus (includes H1 and H2)  27       0.839821
                  Planum Temporale                     27       0.837093
                  Supracalcarine Cortex                27       0.833106
                  Occipital Pole                       27       0.836262

                                                      mean baseline MAE  \
model             brain region
Linear Regression Background                                   0.842854
                  Frontal Pole                                  0.72948
                  Insular Cortex                               0.754798
                  Superior Frontal Gyrus                       0.719737
                  Middle Frontal Gyrus                         0.734678
...                                                                 ...
XGBoost           Planum Polare                                 0.77202
                  Heschl's Gyrus (includes H1 and H2)          0.766299
                  Planum Temporale                             0.759918
                  Supracalcarine Cortex                        0.799145
                  Occipital Pole                               0.793852

                                                      STD model MAE  \
model             brain region
Linear Regression Background                                0.14465
                  Frontal Pole                             0.165448
                  Insular Cortex                           0.124419
                  Superior Frontal Gyrus                   0.157173
                  Middle Frontal Gyrus                     0.132882
...                                                             ...
XGBoost           Planum Polare                            0.080093
                  Heschl's Gyrus (includes H1 and H2)      0.066278
                  Planum Temporale                         0.066885
                  Supracalcarine Cortex                    0.069086
                  Occipital Pole                           0.054556

                                                      STD baseline MAE  \
model             brain region
Linear Regression Background                                  0.018467
                  Frontal Pole                                0.126654
                  Insular Cortex                              0.068886
                  Superior Frontal Gyrus                      0.136084
                  Middle Frontal Gyrus                        0.115156
...                                                                ...
XGBoost           Planum Polare                               0.062904
                  Heschl's Gyrus (includes H1 and H2)         0.053353
                  Planum Temporale                             0.04281
                  Supracalcarine Cortex                        0.05605
                  Occipital Pole                              0.049365

                                                      Wilcoxon W statistic  \
model             brain region
Linear Regression Background                                         196.0
                  Frontal Pole                                       372.0
                  Insular Cortex                                     360.0
                  Superior Frontal Gyrus                             348.0
                  Middle Frontal Gyrus                               375.0
...                                                                    ...
XGBoost           Planum Polare                                      369.0
                  Heschl's Gyrus (includes H1 and H2)                371.0
                  Planum Temporale                                   366.0
                  Supracalcarine Cortex                              289.0
                  Occipital Pole                                     332.0

                                                        p-value CI (lower)  \
model             brain region
Linear Regression Background                           5.70e-01   0.783981
                  Frontal Pole                         1.00e+00   0.841984
                  Insular Cortex                       1.00e+00   0.840499
                  Superior Frontal Gyrus               1.00e+00    0.79668
                  Middle Frontal Gyrus                 1.00e+00   0.854018
...                                                         ...        ...
XGBoost           Planum Polare                        1.00e+00   0.796526
                  Heschl's Gyrus (includes H1 and H2)  1.00e+00   0.813786
                  Planum Temporale                     1.00e+00   0.813749
                  Supracalcarine Cortex                9.93e-01    0.80468
                  Occipital Pole                       1.00e+00   0.816941

                                                      CI (upper)       RBC  \
model             brain region
Linear Regression Background                            0.890761 -0.037037
                  Frontal Pole                           0.96477 -0.968254
                  Insular Cortex                         0.93513 -0.904762
                  Superior Frontal Gyrus                0.910903  -0.84127
                  Middle Frontal Gyrus                  0.951355 -0.984127
...                                                          ...       ...
XGBoost           Planum Polare                         0.858729 -0.952381
                  Heschl's Gyrus (includes H1 and H2)   0.862911 -0.962963
                  Planum Temporale                      0.862748 -0.936508
                  Supracalcarine Cortex                  0.85594 -0.529101
                  Occipital Pole                        0.857795 -0.756614

                                                           CLES
model             brain region
Linear Regression Background                           0.418381
                  Frontal Pole                         0.138546
                  Insular Cortex                       0.133059
                  Superior Frontal Gyrus               0.248285
                  Middle Frontal Gyrus                 0.130316
...                                                         ...
XGBoost           Planum Polare                        0.148148
                  Heschl's Gyrus (includes H1 and H2)  0.185185
                  Planum Temporale                     0.190672
                  Supracalcarine Cortex                0.315501
                  Occipital Pole                       0.308642

[392 rows x 11 columns]

## **2. Deep Learning**

We perform **Wilcoxon signed-rank tests** on the results of the deep learning models for the classification and regression tasks.

### Classification

In [31]:
# Define a function to load the deep learning results for the classification task. 
def load_classification_dl_results(cv_iteration):

    if cv_iteration == 1:
        iteration_result_path = results_path + 'classification/'
        test_set = 'fmriNF'
    elif cv_iteration == 2:
        iteration_result_path = results_path + 'classification/cross_validation/cv_iteration_' + str(cv_iteration) + '/'
        test_set = 'eegfmriNF'
    elif cv_iteration == 3:
        iteration_result_path = results_path + 'classification/cross_validation/cv_iteration_' + str(cv_iteration) + '/'
        test_set = 'eegNF'

    # Load the deep learning results for the classification task. 
    with open(iteration_result_path + 'neural_networks/dict_predictions_neural_networks_class.p', 'rb') as file:
        dict_predictions_neural_networks_class = pickle.load(file)
    with open(iteration_result_path + 'convolutional_neural_networks/dict_predictions_convolutional_neural_networks_class.p', 'rb') as file:
        dict_predictions_convolutional_neural_networks_class = pickle.load(file)
    with open(iteration_result_path + 'recurrent_neural_networks/dict_predictions_recurrent_neural_networks_class.p', 'rb') as file:
        dict_predictions_recurrent_neural_networks_class = pickle.load(file)
    with open(iteration_result_path + 'transformers/dict_predictions_transformers_class.p', 'rb') as file:
        dict_predictions_transformers_class = pickle.load(file)

    return [dict_predictions_neural_networks_class, 
            dict_predictions_convolutional_neural_networks_class, 
            dict_predictions_recurrent_neural_networks_class, 
            dict_predictions_transformers_class, 
            test_set]

In [32]:
# Define a function to run the tests for deep learning classification models.
def run_classification_dl_tests(cv_iteration, model_names):

    # Load the deep learning results for the classification task.
    dict_predictions_neural_networks_class, dict_predictions_convolutional_neural_networks_class, dict_predictions_recurrent_neural_networks_class, dict_predictions_transformers_class, test_set = load_classification_dl_results(cv_iteration)

    predictions_dl_class = [dict_predictions_neural_networks_class, 
                            dict_predictions_convolutional_neural_networks_class, 
                            dict_predictions_recurrent_neural_networks_class, 
                            dict_predictions_transformers_class]

    # Run the Wilcoxon signed-rank tests for all models. 
    df_summary_dl_class, dict_df_metrics_dl_class, _ = run_wilcoxon_tests(model_names, dict_targets_class, predictions_dl_class, brain_regions, 'accuracy', 'deep_learning', test_set)
    
    return df_summary_dl_class, dict_df_metrics_dl_class

In [33]:
# Define the deep learning models for classification. 
model_names = ['Multi-Layer Perceptron', 'Convolutional Neural Network', 'Recurrent Neural Network', 'Transformer']

In [34]:
# Iteration 1: run the tests for deep learning classification models. 
cv_iteration = 1
df_summary_dl_class_iteration_1, dict_df_metrics_dl_class_iteration_1 = run_classification_dl_tests(cv_iteration, model_names)

In [35]:
# Iteration 2: run the tests for deep learning classification models. 
cv_iteration = 2
df_summary_dl_class_iteration_2, dict_df_metrics_dl_class_iteration_2 = run_classification_dl_tests(cv_iteration, model_names)

In [36]:
# Iteration 3: run the tests for deep learning classification models. 
cv_iteration = 3
df_summary_dl_class_iteration_3, dict_df_metrics_dl_class_iteration_3 = run_classification_dl_tests(cv_iteration, model_names)

In [37]:
# Create a dictionary to store the pooled metrics DataFrames for all models. 
dict_df_metrics_dl_class_pooled = {}

# Create a summary DataFrame to store the statistics for all models. 
df_summary_dl_class_pooled = create_summary_df(model_names, 'accuracy', brain_regions)

# Iterate through all models. 
for model_name in model_names:

    # Retrieve the model index.
    model_index = model_names.index(model_name)

    # Pool the metrics DataFrames across cross-validation iterations. 
    df_iteration_1 = dict_df_metrics_dl_class_iteration_1[model_name]
    df_iteration_2 = dict_df_metrics_dl_class_iteration_2[model_name]
    df_iteration_3 = dict_df_metrics_dl_class_iteration_3[model_name]
    df_pooled = pd.concat([df_iteration_1, df_iteration_2, df_iteration_3], ignore_index = True)

    # Perform the Wilcoxon signed-rank test. 
    statistics_scipy, statistics_pingouin = wilcoxon_test(df_pooled, 'accuracy', brain_regions)

    # Store the pooled metrics DataFrame in the dictionary. 
    dict_df_metrics_dl_class_pooled[model_name] = df_pooled

    # Store the statistics in the summary DataFrame. 
    df_summary_dl_class_pooled = store_statistics_in_summary_df(df_summary_dl_class_pooled, model_names, model_index, statistics_scipy, statistics_pingouin, 'accuracy', brain_regions)

In [38]:
# Diplay the pooled summary DataFrame. 
df_summary_dl_class_pooled

                                                             N  \
model                  brain region
Multi-Layer Perceptron Background                           27
                       Frontal Pole                         27
                       Insular Cortex                       27
                       Superior Frontal Gyrus               27
                       Middle Frontal Gyrus                 27
...                                                         ..
Transformer            Planum Polare                        27
                       Heschl's Gyrus (includes H1 and H2)  27
                       Planum Temporale                     27
                       Supracalcarine Cortex                27
                       Occipital Pole                       27

                                                           mean model accuracy  \
model                  brain region
Multi-Layer Perceptron Background                                     0.553837
                       Frontal Pole                                   0.535319
                       Insular Cortex                                 0.513746
                       Superior Frontal Gyrus                         0.536846
                       Middle Frontal Gyrus                           0.539901
...                                                                        ...
Transformer            Planum Polare                                  0.504391
                       Heschl's Gyrus (includes H1 and H2)              0.5021
                       Planum Temporale                               0.506109
                       Supracalcarine Cortex                          0.507446
                       Occipital Pole                                 0.501527

                                                           mean baseline accuracy  \
model                  brain region
Multi-Layer Perceptron Background                                         0.41428
                       Frontal Pole                                      0.511264
                       Insular Cortex                                    0.522719
                       Superior Frontal Gyrus                            0.518328
                       Middle Frontal Gyrus                              0.512218
...                                                                           ...
Transformer            Planum Polare                                     0.506682
                       Heschl's Gyrus (includes H1 and H2)               0.517373
                       Planum Temporale                                  0.507064
                       Supracalcarine Cortex                             0.494654
                       Occipital Pole                                    0.507255

                                                           STD model accuracy  \
model                  brain region
Multi-Layer Perceptron Background                                    0.049655
                       Frontal Pole                                   0.04995
                       Insular Cortex                                0.030729
                       Superior Frontal Gyrus                        0.045021
                       Middle Frontal Gyrus                          0.036661
...                                                                       ...
Transformer            Planum Polare                                 0.026233
                       Heschl's Gyrus (includes H1 and H2)           0.035317
                       Planum Temporale                              0.021964
                       Supracalcarine Cortex                         0.023979
                       Occipital Pole                                0.039692

                                                           STD baseline accuracy  \
model                  brain region
Multi-Layer Perceptron Background                                       0.044045
                       Frontal Pole                                     0.025092
                       Insular Cortex                                   0.031395
                       Superior Frontal Gyrus                           0.023679
                       Middle Frontal Gyrus                              0.02538
...                                                                          ...
Transformer            Planum Polare                                    0.023483
                       Heschl's Gyrus (includes H1 and H2)              0.021308
                       Planum Temporale                                 0.021356
                       Supracalcarine Cortex                            0.020393
                       Occipital Pole                                    0.02324

                                                           Wilcoxon W statistic  \
model                  brain region
Multi-Layer Perceptron Background                                         376.5
                       Frontal Pole                                       283.0
                       Insular Cortex                                     132.5
                       Superior Frontal Gyrus                             245.5
                       Middle Frontal Gyrus                               289.5
...                                                                         ...
Transformer            Planum Polare                                      140.0
                       Heschl's Gyrus (includes H1 and H2)                 73.0
                       Planum Temporale                                   111.0
                       Supracalcarine Cortex                              196.0
                       Occipital Pole                                     116.0

                                                             p-value  \
model                  brain region
Multi-Layer Perceptron Background                           3.32e-06
                       Frontal Pole                         3.14e-03
                       Insular Cortex                       8.63e-01
                       Superior Frontal Gyrus               3.77e-02
                       Middle Frontal Gyrus                 7.86e-03
...                                                              ...
Transformer            Planum Polare                        6.13e-01
                       Heschl's Gyrus (includes H1 and H2)  9.86e-01
                       Planum Temporale                     5.62e-01
                       Supracalcarine Cortex                3.87e-02
                       Occipital Pole                       8.34e-01

                                                           CI (lower)  \
model                  brain region
Multi-Layer Perceptron Background                            0.535892
                       Frontal Pole                          0.516609
                       Insular Cortex                        0.502673
                       Superior Frontal Gyrus                0.520619
                       Middle Frontal Gyrus                  0.525773
...                                                               ...
Transformer            Planum Polare                         0.495227
                       Heschl's Gyrus (includes H1 and H2)   0.488163
                       Planum Temporale                      0.497709
                       Supracalcarine Cortex                 0.499809
                       Occipital Pole                        0.487973

                                                           CI (upper)  \
model                  brain region
Multi-Layer Perceptron Background                            0.572547
                       Frontal Pole                          0.553646
                       Insular Cortex                        0.525391
                       Superior Frontal Gyrus                0.553837
                       Middle Frontal Gyrus                  0.553265
...                                                               ...
Transformer            Planum Polare                         0.514509
                       Heschl's Gyrus (includes H1 and H2)   0.514318
                       Planum Temporale                      0.513937
                       Supracalcarine Cortex                 0.517635
                       Occipital Pole                        0.517946

                                                                 RBC      CLES
model                  brain region
Multi-Layer Perceptron Background                           0.992063  0.991084
                       Frontal Pole                         0.612536  0.675583
                       Insular Cortex                      -0.245014  0.411523
                       Superior Frontal Gyrus                0.39886  0.621399
                       Middle Frontal Gyrus                 0.531746  0.736626
...                                                              ...       ...
Transformer            Planum Polare                       -0.066667  0.473937
                       Heschl's Gyrus (includes H1 and H2) -0.513333  0.386831
                       Planum Temporale                    -0.038961  0.497257
                       Supracalcarine Cortex                 0.42029  0.640604
                       Occipital Pole                      -0.226667  0.408093

[196 rows x 11 columns]

### Regression

In [39]:
# Define a function to load the deep learning results for the regression task. 
def load_regression_dl_results(cv_iteration):

    if cv_iteration == 1:
        iteration_result_path = results_path + 'regression/'
        test_set = 'fmriNF'
    elif cv_iteration == 2:
        iteration_result_path = results_path + 'regression/cross_validation/cv_iteration_' + str(cv_iteration) + '/'
        test_set = 'eegfmriNF'
    elif cv_iteration == 3:
        iteration_result_path = results_path + 'regression/cross_validation/cv_iteration_' + str(cv_iteration) + '/'
        test_set = 'eegNF'

    # Load the deep learning results for the regression task. 
    with open(iteration_result_path + 'neural_networks/dict_predictions_neural_networks_reg.p', 'rb') as file:
        dict_predictions_neural_networks_reg = pickle.load(file)
    with open(iteration_result_path + 'convolutional_neural_networks/dict_predictions_convolutional_neural_networks_reg.p', 'rb') as file:
        dict_predictions_convolutional_neural_networks_reg = pickle.load(file)
    with open(iteration_result_path + 'recurrent_neural_networks/dict_predictions_recurrent_neural_networks_reg.p', 'rb') as file:
        dict_predictions_recurrent_neural_networks_reg = pickle.load(file)
    with open(iteration_result_path + 'transformers/dict_predictions_transformers_reg.p', 'rb') as file:
        dict_predictions_transformers_reg = pickle.load(file)

    return [dict_predictions_neural_networks_reg, 
            dict_predictions_convolutional_neural_networks_reg, 
            dict_predictions_recurrent_neural_networks_reg, 
            dict_predictions_transformers_reg, 
            test_set]

In [40]:
# Define a function to run the tests for deep learning regression models.
def run_regression_dl_tests(cv_iteration, model_names):

    # Load the deep learning results for the regression task.
    dict_predictions_neural_networks_reg, dict_predictions_convolutional_neural_networks_reg, dict_predictions_recurrent_neural_networks_reg, dict_predictions_transformers_reg, test_set = load_regression_dl_results(cv_iteration)

    predictions_dl_reg = [dict_predictions_neural_networks_reg, 
                            dict_predictions_convolutional_neural_networks_reg, 
                            dict_predictions_recurrent_neural_networks_reg, 
                            dict_predictions_transformers_reg]

    # Run the Wilcoxon signed-rank tests for all models. 
    df_summary_dl_reg, dict_df_metrics_dl_reg, dict_all_targets_predictions_dl_reg = run_wilcoxon_tests(model_names, dict_targets_reg, predictions_dl_reg, brain_regions, 'MAE', 'deep_learning', test_set)
    
    return df_summary_dl_reg, dict_df_metrics_dl_reg, dict_all_targets_predictions_dl_reg

In [41]:
# Define the deep learning models for regression. 
model_names = ['Multi-Layer Perceptron', 'Convolutional Neural Network', 'Recurrent Neural Network', 'Transformer']

In [42]:
# Iteration 1: run the tests for deep learning regression models. 
cv_iteration = 1
df_summary_dl_reg_iteration_1, dict_df_metrics_dl_reg_iteration_1, dict_all_targets_predictions_dl_reg_iteration_1 = run_regression_dl_tests(cv_iteration, model_names)

In [43]:
# Iteration 2: run the tests for deep learning regression models. 
cv_iteration = 2
df_summary_dl_reg_iteration_2, dict_df_metrics_dl_reg_iteration_2, dict_all_targets_predictions_dl_reg_iteration_2 = run_regression_dl_tests(cv_iteration, model_names)

In [44]:
# Iteration 3: run the tests for deep learning regression models. 
cv_iteration = 3
df_summary_dl_reg_iteration_3, dict_df_metrics_dl_reg_iteration_3, dict_all_targets_predictions_dl_reg_iteration_3 = run_regression_dl_tests(cv_iteration, model_names)

In [45]:
# Create a dictionary to store the pooled metrics DataFrames for all models. 
dict_df_metrics_dl_reg_pooled = {}

# Create a summary DataFrame to store the statistics for all models. 
df_summary_dl_reg_pooled = create_summary_df(model_names, 'MAE', brain_regions)

# Iterate through all models. 
for model_name in model_names:

    # Retrieve the model index.
    model_index = model_names.index(model_name)

    # Pool the metrics DataFrames across cross-validation iterations. 
    df_iteration_1 = dict_df_metrics_dl_reg_iteration_1[model_name]
    df_iteration_2 = dict_df_metrics_dl_reg_iteration_2[model_name]
    df_iteration_3 = dict_df_metrics_dl_reg_iteration_3[model_name]
    df_pooled = pd.concat([df_iteration_1, df_iteration_2, df_iteration_3], ignore_index = True)

    # Perform the Wilcoxon signed-rank test. 
    statistics_scipy, statistics_pingouin = wilcoxon_test(df_pooled, 'MAE', brain_regions)

    # Store the pooled metrics DataFrame in the dictionary. 
    dict_df_metrics_dl_reg_pooled[model_name] = df_pooled

    # Store the statistics in the summary DataFrame. 
    df_summary_dl_reg_pooled = store_statistics_in_summary_df(df_summary_dl_reg_pooled, model_names, model_index, statistics_scipy, statistics_pingouin, 'MAE', brain_regions)

In [46]:
# Diplay the pooled summary DataFrame. 
df_summary_dl_reg_pooled

                                                             N mean model MAE  \
model                  brain region
Multi-Layer Perceptron Background                           27       0.845659
                       Frontal Pole                         27       0.728018
                       Insular Cortex                       27       0.765594
                       Superior Frontal Gyrus               27       0.733013
                       Middle Frontal Gyrus                 27       0.735631
...                                                         ..            ...
Transformer            Planum Polare                        27       0.784712
                       Heschl's Gyrus (includes H1 and H2)  27       0.784687
                       Planum Temporale                     27        0.76632
                       Supracalcarine Cortex                27       0.799185
                       Occipital Pole                       27       0.785974

                                                           mean baseline MAE  \
model                  brain region
Multi-Layer Perceptron Background                                   0.842854
                       Frontal Pole                                  0.72948
                       Insular Cortex                               0.754798
                       Superior Frontal Gyrus                       0.719737
                       Middle Frontal Gyrus                         0.734678
...                                                                      ...
Transformer            Planum Polare                                 0.77202
                       Heschl's Gyrus (includes H1 and H2)          0.766299
                       Planum Temporale                             0.759918
                       Supracalcarine Cortex                        0.799145
                       Occipital Pole                               0.793852

                                                           STD model MAE  \
model                  brain region
Multi-Layer Perceptron Background                               0.027404
                       Frontal Pole                             0.126874
                       Insular Cortex                           0.072604
                       Superior Frontal Gyrus                   0.143832
                       Middle Frontal Gyrus                     0.115498
...                                                                  ...
Transformer            Planum Polare                            0.072543
                       Heschl's Gyrus (includes H1 and H2)      0.065722
                       Planum Temporale                         0.040772
                       Supracalcarine Cortex                    0.073807
                       Occipital Pole                           0.052904

                                                           STD baseline MAE  \
model                  brain region
Multi-Layer Perceptron Background                                  0.018467
                       Frontal Pole                                0.126654
                       Insular Cortex                              0.068886
                       Superior Frontal Gyrus                      0.136084
                       Middle Frontal Gyrus                        0.115156
...                                                                     ...
Transformer            Planum Polare                               0.062904
                       Heschl's Gyrus (includes H1 and H2)         0.053353
                       Planum Temporale                             0.04281
                       Supracalcarine Cortex                        0.05605
                       Occipital Pole                              0.049365

                                                           Wilcoxon W statistic  \
model                  brain region
Multi-Layer Perceptron Background                                         185.0
                       Frontal Pole                                       160.0
                       Insular Cortex                                     249.0
                       Superior Frontal Gyrus                             290.0
                       Middle Frontal Gyrus                               202.0
...                                                                         ...
Transformer            Planum Polare                                      285.0
                       Heschl's Gyrus (includes H1 and H2)                302.0
                       Planum Temporale                                   245.0
                       Supracalcarine Cortex                              177.0
                       Occipital Pole                                     164.0

                                                             p-value  \
model                  brain region
Multi-Layer Perceptron Background                           4.67e-01
                       Frontal Pole                         2.50e-01
                       Insular Cortex                       9.26e-01
                       Superior Frontal Gyrus               9.93e-01
                       Middle Frontal Gyrus                 6.25e-01
...                                                              ...
Transformer            Planum Polare                        9.91e-01
                       Heschl's Gyrus (includes H1 and H2)  9.97e-01
                       Planum Temporale                     9.11e-01
                       Supracalcarine Cortex                3.93e-01
                       Occipital Pole                       2.81e-01

                                                           CI (lower)  \
model                  brain region
Multi-Layer Perceptron Background                            0.835762
                       Frontal Pole                           0.66629
                       Insular Cortex                        0.730691
                       Superior Frontal Gyrus                0.669072
                       Middle Frontal Gyrus                  0.681302
...                                                               ...
Transformer            Planum Polare                         0.744976
                       Heschl's Gyrus (includes H1 and H2)   0.757071
                       Planum Temporale                      0.750771
                       Supracalcarine Cortex                 0.771183
                       Occipital Pole                        0.766409

                                                           CI (upper)  \
model                  brain region
Multi-Layer Perceptron Background                            0.856059
                       Frontal Pole                          0.764431
                       Insular Cortex                        0.786903
                       Superior Frontal Gyrus                0.778572
                       Middle Frontal Gyrus                    0.7706
...                                                               ...
Transformer            Planum Polare                         0.804229
                       Heschl's Gyrus (includes H1 and H2)   0.806552
                       Planum Temporale                      0.781119
                       Supracalcarine Cortex                 0.826981
                       Occipital Pole                        0.804786

                                                                 RBC      CLES
model                  brain region
Multi-Layer Perceptron Background                           0.021164   0.48834
                       Frontal Pole                         0.153439  0.513032
                       Insular Cortex                       -0.31746  0.427984
                       Superior Frontal Gyrus              -0.534392  0.474623
                       Middle Frontal Gyrus                -0.068783  0.500686
...                                                              ...       ...
Transformer            Planum Polare                       -0.507937  0.375857
                       Heschl's Gyrus (includes H1 and H2) -0.597884  0.384088
                       Planum Temporale                    -0.296296  0.463649
                       Supracalcarine Cortex                0.063492  0.556927
                       Occipital Pole                       0.132275  0.539095

[196 rows x 11 columns]

## **3. Foundation Models**

In [47]:
# Load the foundation models results. 
with open(results_path + 'classification/dict_predictions_gemma.p', 'rb') as file:
    dict_predictions_gemma = pickle.load(file)
with open(results_path + 'classification/dict_predictions_llama.p', 'rb') as file:
    dict_predictions_llama = pickle.load(file)
with open(results_path + 'classification/dict_predictions_gemma_CoT.p', 'rb') as file:
    dict_predictions_gemma_CoT = pickle.load(file)
with open(results_path + 'classification/dict_predictions_gemma_no_finetuning.p', 'rb') as file:
    dict_predictions_gemma_no_finetuning = pickle.load(file)
with open(results_path + 'classification/dict_predictions_gemma_finetuning.p', 'rb') as file:
    dict_predictions_gemma_finetuning = pickle.load(file)
with open(results_path + 'classification/dict_predictions_paligemma.p', 'rb') as file:
    dict_predictions_paligemma = pickle.load(file)
with open(results_path + 'multi-channel/dict_predictions_gemma_5_channels.p', 'rb') as file:
    dict_predictions_gemma_5_channels = pickle.load(file)

# Load the brain regions. 
with open(results_path + 'brain_regions_large_language_models.p', 'rb') as file:
    dict_brain_regions_large_language_models = pickle.load(file)
with open(results_path + 'brain_regions_large_language_model_CoT.p', 'rb') as file:
    dict_brain_regions_large_language_model_CoT = pickle.load(file)
with open(results_path + 'brain_regions_large_language_model_fine-tuning.p', 'rb') as file:
    dict_brain_regions_large_language_model_fine_tuning = pickle.load(file)
with open(results_path + 'brain_regions_large_multimodal_model.p', 'rb') as file:
    dict_brain_regions_large_multimodal_model = pickle.load(file)
with open(results_path + 'multi-channel/brain_regions_multi-channel_large_language_models.p', 'rb') as file:
    dict_brain_regions_multi_channel_large_language_models = pickle.load(file)

# Load the fMRI scans. 
with open(results_path + 'fmri_scans_large_language_models.p', 'rb') as file:
    dict_fmri_scans_large_language_models = pickle.load(file)
with open(results_path + 'fmri_scans_large_language_model_CoT.p', 'rb') as file:
    dict_fmri_scans_large_language_model_CoT = pickle.load(file)
with open(results_path + 'fmri_scans_large_language_model_fine-tuning.p', 'rb') as file:
    dict_fmri_scans_large_language_model_fine_tuning = pickle.load(file)
with open(results_path + 'fmri_scans_large_multimodal_model.p', 'rb') as file:
    dict_fmri_scans_large_multimodal_model = pickle.load(file)
with open(results_path + 'multi-channel/fmri_scans_multi-channel_large_language_models.p', 'rb') as file:
    dict_fmri_scans_multi_channel_large_language_models = pickle.load(file)

In [48]:
# Define the foundation models. 
model_names = ['Gemma', 'Llama', 'Gemma Chain-of-Thought', 'Gemma Without Fine-Tuning', 'Gemma With Fine-Tuning', 'PaliGemma', 'Gemma 5-Channel']
list_dict_predictions = [dict_predictions_gemma, 
                         dict_predictions_llama, 
                         dict_predictions_gemma_CoT, 
                         dict_predictions_gemma_no_finetuning, 
                         dict_predictions_gemma_finetuning, 
                         dict_predictions_paligemma, 
                         dict_predictions_gemma_5_channels]

# Define the brain regions. 
list_brain_regions = [dict_brain_regions_large_language_models['Large Language Models: Gemma'],
                      dict_brain_regions_large_language_models['Large Language Models: Llama'],
                      dict_brain_regions_large_language_model_CoT['Large Language Model Chain-of-Thought'],
                      dict_brain_regions_large_language_model_fine_tuning['Large Language Model Fine-Tuning: Without Fine-Tuning'],
                      dict_brain_regions_large_language_model_fine_tuning['Large Language Model Fine-Tuning: With Fine-Tuning'], 
                      dict_brain_regions_large_multimodal_model['Large Multimodal Model'],
                      dict_brain_regions_multi_channel_large_language_models['Large Language Models: Gemma 5 Channels']]

# Define the fMRI scans indexes. 
list_fmri_scans_indexes = [dict_fmri_scans_large_language_models['Large Language Models: Gemma'],
                           dict_fmri_scans_large_language_models['Large Language Models: Llama'],
                           dict_fmri_scans_large_language_model_CoT['Large Language Model Chain-of-Thought'],
                           dict_fmri_scans_large_language_model_fine_tuning['Large Language Model Fine-Tuning: Without Fine-Tuning'],
                           dict_fmri_scans_large_language_model_fine_tuning['Large Language Model Fine-Tuning: With Fine-Tuning'], 
                           dict_fmri_scans_large_multimodal_model['Large Multimodal Model'], 
                           dict_fmri_scans_multi_channel_large_language_models['Large Language Models: Gemma 5 Channels']]

In [49]:
# Define a function to create the DataFrame for the statistical tests. 
def create_df_foundation_models(dict_targets, dict_predictions, brain_region_indexes, fmri_scans_indexes):
    
    # Define a Pandas DataFrames and two lists to store the results. 
    df = pd.DataFrame(columns = ['subject', 'brain_region', 'model_accuracy', 'baseline_accuracy'])
    list_targets = []
    list_predictions = []
    counter = 0

    # Iterate through all subjects. 
    for subject in subjects:

        # Iterate through all brain regions. 
        for brain_region_index in brain_region_indexes:
            
            # Fill the DataFrame with the subject and brain region. 
            df.loc[counter, 'subject'] = subject
            df.loc[counter, 'brain_region'] = brain_regions[brain_region_index] # Here, brain_regions is the global variable corresponding to all 49 regions. 

            # Retrieve the targets and predictions values for the current subject and brain region. 
            targets_values = dict_targets[subject]['eegfmriNF'][fmri_scans_indexes, brain_region_index]
            predictions_values = dict_predictions[brain_regions[brain_region_index]][subject] # Here, brain_regions is the global variable corresponding to all 49 regions. 

            # Add the targets and predictions to the lists. 
            list_targets.append(targets_values)
            list_predictions.append(predictions_values)

            # Remove the cases where the prediction is -1. 
            selected_predictions = predictions_values != -1
            targets_values = targets_values[selected_predictions]
            predictions_values = predictions_values[selected_predictions]

            # Compute the accuracy and fill in the DataFrame with the model score. 
            model_score = np.mean(targets_values == predictions_values)
            df.loc[counter, 'model_accuracy'] = model_score

            # Define the values and compute the targets distribution. 
            values = [0, 1]
            targets_distribution = [np.sum(targets_values == 0) / len(targets_values), 
                                    np.sum(targets_values == 1) / len(targets_values)]

            # Define the number of iterations. 
            iterations = 1000
            baseline_score = 0

            # Compute the baseline score using random sampling. 
            for i in range(iterations):
                samples = np.random.choice(values, size = len(targets_values), p = targets_distribution)
                baseline_score += np.mean(targets_values == samples)

            # Compute the mean baseline score. 
            baseline_score /= iterations

            # Fill in the DataFrame with the baseline score. 
            df.loc[counter, 'baseline_accuracy'] = baseline_score

            # Increment. 
            counter += 1

    return df, list_targets, list_predictions

In [50]:
# Create a function to retrieve foundation model elements. 
def retrieve_foundation_model_elements(model_index, list_dict_predictions, list_brain_regions, list_fmri_scans_indexes):

    # Retrieve the foundation model elements. 
    dict_predictions = list_dict_predictions[model_index]
    brain_region_indexes = [brain_regions.index(region) for region in list_brain_regions[model_index]] # Here, brain_regions is the global variable corresponding to all 49 regions. 
    fmri_scans_indexes = list_fmri_scans_indexes[model_index]

    return dict_predictions, brain_region_indexes, fmri_scans_indexes

In [51]:
# Example: Create and display the DataFrame for the Gemma model. 
model_index = 0
dict_predictions, brain_region_indexes, fmri_scans_indexes = retrieve_foundation_model_elements(model_index, 
                                                                                                list_dict_predictions,
                                                                                                list_brain_regions,
                                                                                                list_fmri_scans_indexes)

# Create and display the DataFrame. 
df_gemma, _, _ = create_df_foundation_models(dict_targets_foundation_models, 
                                             dict_predictions, 
                                             brain_region_indexes, 
                                             fmri_scans_indexes)
df_gemma

,subject,brain_region,model_accuracy,baseline_accuracy
0,sub-xp101,Frontal Pole,0.35,0.50555
1,sub-xp101,Insular Cortex,0.65,0.50665
2,sub-xp101,"Inferior Frontal Gyrus, pars triangularis",0.55,0.50885
3,sub-xp101,Precentral Gyrus,0.529412,0.583941
4,sub-xp101,"Superior Temporal Gyrus, posterior division",0.4,0.5008
...,...,...,...,...
67,sub-xp110,Precentral Gyrus,0.45,0.52415
68,sub-xp110,"Superior Temporal Gyrus, posterior division",0.45,0.50355
69,sub-xp110,Superior Parietal Lobule,0.6,0.5056
70,sub-xp110,Angular Gyrus,0.210526,0.513158
71,sub-xp110,Occipital Pole,0.6,0.58015

In [52]:
# Perform Wilcoxon signed-rank test. 
statistics_scipy_gemma, statistics_pingouin_gemma = wilcoxon_test(df_gemma, 'accuracy', brain_regions = df_gemma['brain_region'].unique())

In [53]:
# Display the SciPy statistics. 
statistics_scipy_gemma

,brain_region,N,mean_model_accuracy,mean_baseline_accuracy,std_model_accuracy,std_baseline_accuracy,wilcoxon_stat,p_value,ci_low,ci_high
0,Frontal Pole,9,0.547739,0.506676,0.113851,0.005492,33.0,0.125000,0.476979,0.616695
1,Insular Cortex,9,0.516667,0.519978,0.099084,0.036330,22.0,0.544922,0.454548,0.576902
2,"Inferior Frontal Gyrus, pars triangularis",9,0.504971,0.529738,0.125142,0.043106,20.0,0.632812,0.428363,0.580702
3,Precentral Gyrus,9,0.517068,0.539728,0.113596,0.043439,17.0,0.751953,0.445894,0.585091
4,"Superior Temporal Gyrus, posterior division",9,0.520825,0.532659,0.072325,0.035742,23.0,0.500000,0.475763,0.563548
5,Superior Parietal Lobule,9,0.556725,0.541408,0.066857,0.057345,28.0,0.285156,0.513093,0.595906
6,Angular Gyrus,9,0.502989,0.520001,0.131990,0.021964,24.0,0.455078,0.388304,0.565238
7,Occipital Pole,9,0.606140,0.540448,0.106992,0.027748,36.0,0.064453,0.533918,0.665789

In [54]:
# Display the Pingouin statistics. 
statistics_pingouin_gemma

,brain_region,W-val,alternative,p-val,RBC,CLES
0,Frontal Pole,33.0,greater,0.125000,0.466667,0.666667
1,Insular Cortex,22.0,greater,0.544922,-0.022222,0.506173
2,"Inferior Frontal Gyrus, pars triangularis",20.0,greater,0.632812,-0.111111,0.407407
3,Precentral Gyrus,17.0,greater,0.751953,-0.244444,0.456790
4,"Superior Temporal Gyrus, posterior division",23.0,greater,0.500000,0.022222,0.518519
5,Superior Parietal Lobule,28.0,greater,0.285156,0.244444,0.580247
6,Angular Gyrus,24.0,greater,0.455078,0.066667,0.580247
7,Occipital Pole,36.0,greater,0.064453,0.600000,0.765432

In [55]:
# Define a function to perform a Wilcoxon signed-rank test on a series of models. 
def run_wilcoxon_tests_foundation_models(model_names, dict_targets, list_dict_predictions, list_brain_regions, list_fmri_scans_indexes):

    # Define the brain regions, assuming they are the same for all models. 
    brain_regions_foundation_models = list_brain_regions[0]

    # Create a summary DataFrame to store the statistics for all models. 
    df_summary = create_summary_df(model_names, 'accuracy', brain_regions_foundation_models)

    # Iterate through all models. 
    for model_index in range(len(model_names)):

        # Retrieve the predictions, brain region indexes, and fMRI scans indexes. 
        dict_predictions, brain_region_indexes, fmri_scans_indexes = retrieve_foundation_model_elements(model_index, 
                                                                                                        list_dict_predictions,
                                                                                                        list_brain_regions,
                                                                                                        list_fmri_scans_indexes)

        # Create the DataFrame and perform the Wilcoxon signed-rank test. 
        df, _, _ = create_df_foundation_models(dict_targets, dict_predictions, brain_region_indexes, fmri_scans_indexes)
        statistics_scipy, statistics_pingouin = wilcoxon_test(df, 'accuracy', brain_regions_foundation_models)

        # Store the statistics in the summary DataFrame. 
        df_summary = store_statistics_in_summary_df(df_summary, model_names, model_index, statistics_scipy, statistics_pingouin, 'accuracy', brain_regions_foundation_models)
        
    # Return the summary DataFrame. 
    return df_summary

In [56]:
# Identify the models with 8 regions. 
models_with_8_regions = ['Gemma', 'Llama', 'PaliGemma', 'Gemma 5-Channel']
indexes_models_with_8_regions = [model_names.index(model_name) for model_name in models_with_8_regions]

# Select the predictions, brain regions, and fMRI scans for the models with 8 regions. 
list_dict_predictions_8_regions = [list_dict_predictions[i] for i in indexes_models_with_8_regions]
list_brain_regions_8_regions = [list_brain_regions[i] for i in indexes_models_with_8_regions]
list_fmri_scans_indexes_8_regions = [list_fmri_scans_indexes[i] for i in indexes_models_with_8_regions]

# Run the Wilcoxon signed-rank tests for models with 8 regions. 
df_summary_foundation_models_8_regions = run_wilcoxon_tests_foundation_models(models_with_8_regions, 
                                                                              dict_targets_foundation_models, 
                                                                              list_dict_predictions_8_regions, 
                                                                              list_brain_regions_8_regions,
                                                                              list_fmri_scans_indexes_8_regions)
df_summary_foundation_models_8_regions

                                                             N  \
model           brain region
Gemma           Frontal Pole                                 9
                Insular Cortex                               9
                Inferior Frontal Gyrus, pars triangularis    9
                Precentral Gyrus                             9
                Superior Temporal Gyrus, posterior division  9
                Superior Parietal Lobule                     9
                Angular Gyrus                                9
                Occipital Pole                               9
Llama           Frontal Pole                                 9
                Insular Cortex                               9
                Inferior Frontal Gyrus, pars triangularis    9
                Precentral Gyrus                             9
                Superior Temporal Gyrus, posterior division  9
                Superior Parietal Lobule                     9
                Angular Gyrus                                9
                Occipital Pole                               9
PaliGemma       Frontal Pole                                 9
                Insular Cortex                               9
                Inferior Frontal Gyrus, pars triangularis    9
                Precentral Gyrus                             9
                Superior Temporal Gyrus, posterior division  9
                Superior Parietal Lobule                     9
                Angular Gyrus                                9
                Occipital Pole                               9
Gemma 5-Channel Frontal Pole                                 9
                Insular Cortex                               9
                Inferior Frontal Gyrus, pars triangularis    9
                Precentral Gyrus                             9
                Superior Temporal Gyrus, posterior division  9
                Superior Parietal Lobule                     9
                Angular Gyrus                                9
                Occipital Pole                               9

                                                            mean model accuracy  \
model           brain region
Gemma           Frontal Pole                                           0.547739
                Insular Cortex                                         0.516667
                Inferior Frontal Gyrus, pars triangularis              0.504971
                Precentral Gyrus                                       0.517068
                Superior Temporal Gyrus, posterior division            0.520825
                Superior Parietal Lobule                               0.556725
                Angular Gyrus                                          0.502989
                Occipital Pole                                          0.60614
Llama           Frontal Pole                                           0.507276
                Insular Cortex                                         0.472986
                Inferior Frontal Gyrus, pars triangularis              0.534698
                Precentral Gyrus                                       0.500677
                Superior Temporal Gyrus, posterior division            0.461763
                Superior Parietal Lobule                               0.528772
                Angular Gyrus                                          0.543137
                Occipital Pole                                         0.528162
PaliGemma       Frontal Pole                                           0.427513
                Insular Cortex                                         0.529938
                Inferior Frontal Gyrus, pars triangularis               0.48858
                Precentral Gyrus                                       0.456481
                Superior Temporal Gyrus, posterior division            0.495062
                Superior Parietal Lobule                               0.476235
                Angular Gyrus                                          0.459877
                Occipital Pole                                         0.485185
Gemma 5-Channel Frontal Pole                                             0.5282
                Insular Cortex                                         0.460974
                Inferior Frontal Gyrus, pars triangularis               0.46178
                Precentral Gyrus                                       0.520282
                Superior Temporal Gyrus, posterior division            0.539126
                Superior Parietal Lobule                               0.521913
                Angular Gyrus                                          0.472942
                Occipital Pole                                         0.514945

                                                            mean baseline accuracy  \
model           brain region
Gemma           Frontal Pole                                               0.50617
                Insular Cortex                                            0.520042
                Inferior Frontal Gyrus, pars triangularis                 0.531055
                Precentral Gyrus                                          0.540172
                Superior Temporal Gyrus, posterior division               0.531641
                Superior Parietal Lobule                                  0.539717
                Angular Gyrus                                             0.518474
                Occipital Pole                                            0.540625
Llama           Frontal Pole                                              0.511938
                Insular Cortex                                            0.529714
                Inferior Frontal Gyrus, pars triangularis                 0.533485
                Precentral Gyrus                                          0.542101
                Superior Temporal Gyrus, posterior division               0.530541
                Superior Parietal Lobule                                  0.539968
                Angular Gyrus                                             0.522965
                Occipital Pole                                            0.540079
PaliGemma       Frontal Pole                                               0.55001
                Insular Cortex                                            0.536352
                Inferior Frontal Gyrus, pars triangularis                 0.590239
                Precentral Gyrus                                          0.624111
                Superior Temporal Gyrus, posterior division               0.595099
                Superior Parietal Lobule                                  0.647091
                Angular Gyrus                                             0.583113
                Occipital Pole                                            0.555912
Gemma 5-Channel Frontal Pole                                              0.504547
                Insular Cortex                                             0.52457
                Inferior Frontal Gyrus, pars triangularis                 0.528185
                Precentral Gyrus                                          0.543448
                Superior Temporal Gyrus, posterior division               0.529339
                Superior Parietal Lobule                                  0.555893
                Angular Gyrus                                             0.519249
                Occipital Pole                                            0.540685

                                                            STD model accuracy  \
model           brain region
Gemma           Frontal Pole                                          0.113851
                Insular Cortex                                        0.099084
                Inferior Frontal Gyrus, pars triangularis             0.125142
                Precentral Gyrus                                      0.113596
                Superior Temporal Gyrus, posterior division           0.072325
                Superior Parietal Lobule                              0.066857
                Angular Gyrus                                          0.13199
                Occipital Pole                                        0.106992
Llama           Frontal Pole                                          0.076532
                Insular Cortex                                        0.196111
                Inferior Frontal Gyrus, pars triangularis              0.08291
                Precentral Gyrus                                      0.118697
                Superior Temporal Gyrus, posterior division           0.165815
                Superior Parietal Lobule                              0.141992
                Angular Gyrus                                         0.101503
                Occipital Pole                                         0.13136
PaliGemma       Frontal Pole                                          0.140393
                Insular Cortex                                        0.120967
                Inferior Frontal Gyrus, pars triangularis             0.161162
                Precentral Gyrus                                      0.170805
                Superior Temporal Gyrus, posterior division           0.093477
                Superior Parietal Lobule                              0.200439
                Angular Gyrus                                         0.118114
                Occipital Pole                                        0.142292
Gemma 5-Channel Frontal Pole                                          0.106484
                Insular Cortex                                        0.142269
                Inferior Frontal Gyrus, pars triangularis             0.155568
                Precentral Gyrus                                      0.089751
                Superior Temporal Gyrus, posterior division           0.148855
                Superior Parietal Lobule                              0.100595
                Angular Gyrus                                         0.110004
                Occipital Pole                                        0.083763

                                                            STD baseline accuracy  \
model           brain region
Gemma           Frontal Pole                                             0.006019
                Insular Cortex                                           0.034915
                Inferior Frontal Gyrus, pars triangularis                0.045372
                Precentral Gyrus                                          0.04239
                Superior Temporal Gyrus, posterior division              0.036474
                Superior Parietal Lobule                                 0.059538
                Angular Gyrus                                            0.021534
                Occipital Pole                                           0.030073
Llama           Frontal Pole                                             0.009008
                Insular Cortex                                           0.036108
                Inferior Frontal Gyrus, pars triangularis                0.043472
                Precentral Gyrus                                         0.040045
                Superior Temporal Gyrus, posterior division              0.034866
                Superior Parietal Lobule                                 0.058789
                Angular Gyrus                                            0.021547
                Occipital Pole                                           0.032134
PaliGemma       Frontal Pole                                             0.041029
                Insular Cortex                                           0.025987
                Inferior Frontal Gyrus, pars triangularis                0.156315
                Precentral Gyrus                                         0.173768
                Superior Temporal Gyrus, posterior division              0.104869
                Superior Parietal Lobule                                 0.180172
                Angular Gyrus                                            0.100921
                Occipital Pole                                           0.067721
Gemma 5-Channel Frontal Pole                                             0.006781
                Insular Cortex                                           0.039741
                Inferior Frontal Gyrus, pars triangularis                0.042623
                Precentral Gyrus                                         0.042756
                Superior Temporal Gyrus, posterior division               0.03697
                Superior Parietal Lobule                                 0.067967
                Angular Gyrus                                             0.01747
                Occipital Pole                                           0.032823

                                                            Wilcoxon W statistic  \
model           brain region
Gemma           Frontal Pole                                                33.0
                Insular Cortex                                              22.0
                Inferior Frontal Gyrus, pars triangularis                   20.0
                Precentral Gyrus                                            17.0
                Superior Temporal Gyrus, posterior division                 23.0
                Superior Parietal Lobule                                    31.0
                Angular Gyrus                                               24.0
                Occipital Pole                                              36.0
Llama           Frontal Pole                                                29.0
                Insular Cortex                                              14.0
                Inferior Frontal Gyrus, pars triangularis                   24.0
                Precentral Gyrus                                            15.0
                Superior Temporal Gyrus, posterior division                 15.0
                Superior Parietal Lobule                                    26.0
                Angular Gyrus                                               26.0
                Occipital Pole                                              17.0
PaliGemma       Frontal Pole                                                 6.0
                Insular Cortex                                              30.0
                Inferior Frontal Gyrus, pars triangularis                    9.0
                Precentral Gyrus                                             9.0
                Superior Temporal Gyrus, posterior division                  6.0
                Superior Parietal Lobule                                    12.0
                Angular Gyrus                                                8.0
                Occipital Pole                                              11.0
Gemma 5-Channel Frontal Pole                                                28.0
                Insular Cortex                                              12.0
                Inferior Frontal Gyrus, pars triangularis                   14.0
                Precentral Gyrus                                            17.0
                Superior Temporal Gyrus, posterior division                 17.0
                Superior Parietal Lobule                                    18.0
                Angular Gyrus                                               15.0
                Occipital Pole                                              13.0

                                                              p-value  \
model           brain region
Gemma           Frontal Pole                                 1.25e-01
                Insular Cortex                               5.45e-01
                Inferior Frontal Gyrus, pars triangularis    6.33e-01
                Precentral Gyrus                             7.52e-01
                Superior Temporal Gyrus, posterior division  5.00e-01
                Superior Parietal Lobule                     1.80e-01
                Angular Gyrus                                4.55e-01
                Occipital Pole                               6.45e-02
Llama           Frontal Pole                                 2.48e-01
                Insular Cortex                               8.50e-01
                Inferior Frontal Gyrus, pars triangularis    4.55e-01
                Precentral Gyrus                             8.20e-01
                Superior Temporal Gyrus, posterior division  8.20e-01
                Superior Parietal Lobule                     3.67e-01
                Angular Gyrus                                3.67e-01
                Occipital Pole                               7.52e-01
PaliGemma       Frontal Pole                                 9.80e-01
                Insular Cortex                               2.13e-01
                Inferior Frontal Gyrus, pars triangularis    9.51e-01
                Precentral Gyrus                             9.51e-01
                Superior Temporal Gyrus, posterior division  9.80e-01
                Superior Parietal Lobule                     8.98e-01
                Angular Gyrus                                9.63e-01
                Occipital Pole                               9.18e-01
Gemma 5-Channel Frontal Pole                                 2.85e-01
                Insular Cortex                               8.98e-01
                Inferior Frontal Gyrus, pars triangularis    8.50e-01
                Precentral Gyrus                             7.52e-01
                Superior Temporal Gyrus, posterior division  7.52e-01
                Superior Parietal Lobule                     7.15e-01
                Angular Gyrus                                8.20e-01
                Occipital Pole                               8.75e-01

                                                            CI (lower)  \
model           brain region
Gemma           Frontal Pole                                  0.477415
                Insular Cortex                                0.454541
                Inferior Frontal Gyrus, pars triangularis     0.428363
                Precentral Gyrus                              0.445031
                Superior Temporal Gyrus, posterior division    0.47781
                Superior Parietal Lobule                      0.513385
                Angular Gyrus                                 0.396556
                Occipital Pole                                0.534617
Llama           Frontal Pole                                  0.430192
                Insular Cortex                                0.362225
                Inferior Frontal Gyrus, pars triangularis     0.484292
                Precentral Gyrus                              0.429519
                Superior Temporal Gyrus, posterior division   0.368515
                Superior Parietal Lobule                       0.42802
                Angular Gyrus                                  0.49343
                Occipital Pole                                0.459286
PaliGemma       Frontal Pole                                   0.33933
                Insular Cortex                                0.401821
                Inferior Frontal Gyrus, pars triangularis     0.395062
                Precentral Gyrus                               0.37037
                Superior Temporal Gyrus, posterior division   0.445679
                Superior Parietal Lobule                      0.349218
                Angular Gyrus                                 0.383642
                Occipital Pole                                0.401235
Gemma 5-Channel Frontal Pole                                  0.455556
                Insular Cortex                                0.376623

In [57]:
# Identify the models with 5 regions. 
models_with_5_regions = ['Gemma Chain-of-Thought', 'Gemma Without Fine-Tuning', 'Gemma With Fine-Tuning']
indexes_models_with_5_regions = [model_names.index(model_name) for model_name in models_with_5_regions]

# Select the predictions, brain regions, and fMRI scans for the models with 5 regions. 
list_dict_predictions_5_regions = [list_dict_predictions[i] for i in indexes_models_with_5_regions]
list_brain_regions_5_regions = [list_brain_regions[i] for i in indexes_models_with_5_regions]
list_fmri_scans_indexes_5_regions = [list_fmri_scans_indexes[i] for i in indexes_models_with_5_regions]

# Run the Wilcoxon signed-rank tests for models with 5 regions. 
df_summary_foundation_models_5_regions = run_wilcoxon_tests_foundation_models(models_with_5_regions, 
                                                                              dict_targets_foundation_models, 
                                                                              list_dict_predictions_5_regions, 
                                                                              list_brain_regions_5_regions,
                                                                              list_fmri_scans_indexes_5_regions)
df_summary_foundation_models_5_regions

                                                                       N  \
model                     brain region
Gemma Chain-of-Thought    Frontal Pole                                 9
                          Precentral Gyrus                             9
                          Superior Temporal Gyrus, posterior division  9
                          Superior Parietal Lobule                     9
                          Occipital Pole                               9
Gemma Without Fine-Tuning Frontal Pole                                 9
                          Precentral Gyrus                             9
                          Superior Temporal Gyrus, posterior division  9
                          Superior Parietal Lobule                     9
                          Occipital Pole                               9
Gemma With Fine-Tuning    Frontal Pole                                 9
                          Precentral Gyrus                             9
                          Superior Temporal Gyrus, posterior division  9
                          Superior Parietal Lobule                     9
                          Occipital Pole                               9

                                                                      mean model accuracy  \
model                     brain region
Gemma Chain-of-Thought    Frontal Pole                                           0.495108
                          Precentral Gyrus                                       0.597953
                          Superior Temporal Gyrus, posterior division            0.527959
                          Superior Parietal Lobule                               0.539409
                          Occipital Pole                                         0.562736
Gemma Without Fine-Tuning Frontal Pole                                           0.529654
                          Precentral Gyrus                                        0.57076
                          Superior Temporal Gyrus, posterior division            0.525276
                          Superior Parietal Lobule                                0.55679
                          Occipital Pole                                         0.542982
Gemma With Fine-Tuning    Frontal Pole                                           0.471637
                          Precentral Gyrus                                       0.594899
                          Superior Temporal Gyrus, posterior division            0.528687
                          Superior Parietal Lobule                                0.58681
                          Occipital Pole                                          0.55369

                                                                      mean baseline accuracy  \
model                     brain region
Gemma Chain-of-Thought    Frontal Pole                                              0.506453
                          Precentral Gyrus                                          0.535631
                          Superior Temporal Gyrus, posterior division               0.529547
                          Superior Parietal Lobule                                  0.538205
                          Occipital Pole                                            0.545215
Gemma Without Fine-Tuning Frontal Pole                                              0.507328
                          Precentral Gyrus                                          0.542402
                          Superior Temporal Gyrus, posterior division               0.529853
                          Superior Parietal Lobule                                  0.539211
                          Occipital Pole                                            0.543706
Gemma With Fine-Tuning    Frontal Pole                                              0.510884
                          Precentral Gyrus                                          0.546805
                          Superior Temporal Gyrus, posterior division                0.52285
                          Superior Parietal Lobule                                  0.537656
                          Occipital Pole                                            0.550329

                                                                      STD model accuracy  \
model                     brain region
Gemma Chain-of-Thought    Frontal Pole                                          0.139532
                          Precentral Gyrus                                      0.065655
                          Superior Temporal Gyrus, posterior division           0.129459
                          Superior Parietal Lobule                              0.143443
                          Occipital Pole                                        0.089293
Gemma Without Fine-Tuning Frontal Pole                                          0.113806
                          Precentral Gyrus                                      0.082292
                          Superior Temporal Gyrus, posterior division           0.128276
                          Superior Parietal Lobule                              0.110438
                          Occipital Pole                                        0.155475
Gemma With Fine-Tuning    Frontal Pole                                          0.124839
                          Precentral Gyrus                                       0.16456
                          Superior Temporal Gyrus, posterior division           0.152485
                          Superior Parietal Lobule                              0.099688
                          Occipital Pole                                        0.101006

                                                                      STD baseline accuracy  \
model                     brain region
Gemma Chain-of-Thought    Frontal Pole                                             0.008377
                          Precentral Gyrus                                         0.038692
                          Superior Temporal Gyrus, posterior division              0.046082
                          Superior Parietal Lobule                                 0.056559
                          Occipital Pole                                           0.034951
Gemma Without Fine-Tuning Frontal Pole                                              0.01142
                          Precentral Gyrus                                         0.039854
                          Superior Temporal Gyrus, posterior division              0.041299
                          Superior Parietal Lobule                                 0.055428
                          Occipital Pole                                           0.029779
Gemma With Fine-Tuning    Frontal Pole                                             0.015041
                          Precentral Gyrus                                          0.05616
                          Superior Temporal Gyrus, posterior division              0.033583
                          Superior Parietal Lobule                                 0.058224
                          Occipital Pole                                           0.048394

                                                                      Wilcoxon W statistic  \
model                     brain region
Gemma Chain-of-Thought    Frontal Pole                                                21.0
                          Precentral Gyrus                                            37.0
                          Superior Temporal Gyrus, posterior division                 23.0
                          Superior Parietal Lobule                                    19.0
                          Occipital Pole                                              29.0
Gemma Without Fine-Tuning Frontal Pole                                                27.0
                          Precentral Gyrus                                            33.0
                          Superior Temporal Gyrus, posterior division                 26.0
                          Superior Parietal Lobule                                    29.0
                          Occipital Pole                                              20.0
Gemma With Fine-Tuning    Frontal Pole                                                14.0
                          Precentral Gyrus                                            32.0
                          Superior Temporal Gyrus, posterior division                 25.0
                          Superior Parietal Lobule                                    35.0
                          Occipital Pole                                              26.0

                                                                        p-value  \
model                     brain region
Gemma Chain-of-Thought    Frontal Pole                                 5.90e-01
                          Precentral Gyrus                             4.88e-02
                          Superior Temporal Gyrus, posterior division  5.00e-01
                          Superior Parietal Lobule                     6.74e-01
                          Occipital Pole                               2.48e-01
Gemma Without Fine-Tuning Frontal Pole                                 3.26e-01
                          Precentral Gyrus                             1.25e-01
                          Superior Temporal Gyrus, posterior division  3.67e-01
                          Superior Parietal Lobule                     2.48e-01
                          Occipital Pole                               6.33e-01
Gemma With Fine-Tuning    Frontal Pole                                 8.50e-01
                          Precentral Gyrus                             1.50e-01
                          Superior Temporal Gyrus, posterior division  4.10e-01
                          Superior Parietal Lobule                     8.20e-02
                          Occipital Pole                               3.67e-01

                                                                      CI (lower)  \
model                     brain region
Gemma Chain-of-Thought    Frontal Pole                                  0.409344
                          Precentral Gyrus                              0.554094
                          Superior Temporal Gyrus, posterior division    0.44321
                          Superior Parietal Lobule                      0.467934
                          Occipital Pole                                0.506758
Gemma Without Fine-Tuning Frontal Pole                                  0.464614
                          Precentral Gyrus                              0.522807
                          Superior Temporal Gyrus, posterior division   0.427778
                          Superior Parietal Lobule                      0.467674
                          Occipital Pole                                0.461696
Gemma With Fine-Tuning    Frontal Pole                                  0.390643
                          Precentral Gyrus                              0.498456
                          Superior Temporal Gyrus, posterior division   0.421408
                          Superior Parietal Lobule                      0.522742
                          Occipital Pole                                0.495425

                                                                      CI (upper)  \
model                     brain region
Gemma Chain-of-Thought    Frontal Pole                                  0.579474
                          Precentral Gyrus                              0.635579
                          Superior Temporal Gyrus, posterior division   0.604938
                          Superior Parietal Lobule                      0.650237
                          Occipital Pole                                0.617089
Gemma Without Fine-Tuning Frontal Pole                                  0.605375
                          Precentral Gyrus                              0.622515
                          Superior Temporal Gyrus, posterior division   0.590773
                          Superior Parietal Lobule                      0.610526
                          Occipital Pole                                0.659357
Gemma With Fine-Tuning    Frontal Pole                                   0.54386
                          Precentral Gyrus                              0.696816
                          Superior Temporal Gyrus, posterior division   0.609877
                          Superior Parietal Lobule                      0.646491
                          Occipital Pole                                0.619979

                                                                            RBC  \
model                     brain region
Gemma Chain-of-Thought    Frontal Pole                                -0.066667
                          Precentral Gyrus                             0.644444
                          Superior Temporal Gyrus, posterior division  0.022222
                          Superior Parietal Lobule                    -0.155556
                          Occipital Pole                               0.288889
Gemma Without Fine-Tuning Frontal Pole                                      0.2
                          Precentral Gyrus                             0.466667
                          Superior Temporal Gyrus, posterior division  0.155556
                          Superior Parietal Lobule                     0.288889
                          Occipital Pole                              -0.111111
Gemma With Fine-Tuning    Frontal Pole                                -0.377778
                          Precentral Gyrus                             0.422222
                          Superior Temporal Gyrus, posterior division  0.111111
                          Superior Parietal Lobule                     0.555556
                          Occipital Pole                               0.155556

                                                                           CLES
model                     brain region
Gemma Chain-of-Thought    Frontal Pole                                 0.469136
                          Precentral Gyrus                             0.802469
                          Superior Temporal Gyrus, posterior division  0.518519
                          Superior Parietal Lobule                     0.444444
                          Occipital Pole                               0.604938
Gemma Without Fine-Tuning Frontal Pole                                 0.580247
                          Precentral Gyrus                             0.567901
                          Superior Temporal Gyrus, posterior division  0.518519
                          Superior Parietal Lobule                      0.62963
                          Occipital Pole                               0.481481
Gemma With Fine-Tuning    Frontal Pole                                 0.308642
                          Precentral Gyrus                             0.580247
                          Superior Temporal Gyrus, posterior division  0.654321
                          Superior Parietal Lobule                     0.654321
                          Occipital Pole                               0.506173

## **4. Results**

In [58]:
# If the cross-validation results path does not exist, create it. 
if not os.path.exists(results_path + 'regions_of_interest/'):
    os.makedirs(results_path + 'regions_of_interest/')
    
# Store the general results in a dictionary. 
general_results = dict()
general_results['df_summary_ml_class_pooled'] = df_summary_ml_class_pooled
general_results['df_summary_ml_reg_pooled'] = df_summary_ml_reg_pooled
general_results['df_summary_dl_class_pooled'] = df_summary_dl_class_pooled
general_results['df_summary_dl_reg_pooled'] = df_summary_dl_reg_pooled
general_results['df_summary_foundation_models_8_regions'] = df_summary_foundation_models_8_regions
general_results['df_summary_foundation_models_5_regions'] = df_summary_foundation_models_5_regions

# Save the general results into a Pickle file. 
with open(results_path + 'regions_of_interest/general_results.p', 'wb') as file:
    pickle.dump(general_results, file)

In [59]:
# Display the keys of the general results dictionary. 
list(general_results.keys())

['df_summary_ml_class_pooled',
 'df_summary_ml_reg_pooled',
 'df_summary_dl_class_pooled',
 'df_summary_dl_reg_pooled',
 'df_summary_foundation_models_8_regions',
 'df_summary_foundation_models_5_regions']